"""Card definitions.

Each entry is pure data plus an `fx(combat, card, target)` callable. `card.v(a, b)`
picks the base or upgraded value. Optional keys: `ucost`, `rarity`, `exhaust`,
`targeted`, `playable`, `upgradable`, `udesc`, `requires`.

`requires` names an extra choice the player must supply alongside the play action
(currently only "exhaust", for True Grit). The engine never prompts for it — the
client sends it with the action.
"""

CARDS = {
    # ── starter ──
    "strike": dict(name="Strike", type="ATTACK", cost=1, targeted=True, rarity="starter",
                   desc="Deal 6 damage.", udesc="Deal 9 damage.",
                   fx=lambda cb, k, t: cb.player_attack(t, k.v(6, 9))),
    "defend": dict(name="Defend", type="SKILL", cost=1, rarity="starter",
                   desc="Gain 5 Block.", udesc="Gain 8 Block.",
                   fx=lambda cb, k, t: cb.gain_block(cb.player, k.v(5, 8))),
    "bash": dict(name="Bash", type="ATTACK", cost=2, targeted=True, rarity="starter",
                 desc="Deal 8 damage. Apply 2 Vulnerable.",
                 udesc="Deal 10 damage. Apply 3 Vulnerable.",
                 fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 10)),
                                      cb.apply(t, "vulnerable", k.v(2, 3)))),
    # ── common ──
    "cleave": dict(name="Cleave", type="ATTACK", cost=1,
                   desc="Deal 8 damage to ALL enemies.", udesc="Deal 11 damage to ALL enemies.",
                   fx=lambda cb, k, t: [cb.player_attack(e, k.v(8, 11)) for e in cb.living()]),
    "twin_strike": dict(name="Twin Strike", type="ATTACK", cost=1, targeted=True,
                        desc="Deal 5 damage twice.", udesc="Deal 7 damage twice.",
                        fx=lambda cb, k, t: cb.player_attack(t, k.v(5, 7), times=2)),
    "pommel_strike": dict(name="Pommel Strike", type="ATTACK", cost=1, targeted=True,
                          desc="Deal 9 damage. Draw 1 card.",
                          udesc="Deal 10 damage. Draw 2 cards.",
                          fx=lambda cb, k, t: (cb.player_attack(t, k.v(9, 10)),
                                               cb.draw(k.v(1, 2)))),
    "iron_wave": dict(name="Iron Wave", type="ATTACK", cost=1, targeted=True,
                      desc="Gain 5 Block. Deal 5 damage.", udesc="Gain 7 Block. Deal 7 damage.",
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(5, 7)),
                                           cb.player_attack(t, k.v(5, 7)))),
    "clothesline": dict(name="Clothesline", type="ATTACK", cost=2, targeted=True,
                        desc="Deal 12 damage. Apply 2 Weak.",
                        udesc="Deal 14 damage. Apply 3 Weak.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(12, 14)),
                                             cb.apply(t, "weak", k.v(2, 3)))),
    "body_slam": dict(name="Body Slam", type="ATTACK", cost=1, ucost=0, targeted=True,
                      desc="Deal damage equal to your Block.",
                      udesc="Deal damage equal to your Block.",
                      fx=lambda cb, k, t: cb.player_attack(t, cb.player.block)),
    "shrug_it_off": dict(name="Shrug It Off", type="SKILL", cost=1,
                         desc="Gain 8 Block. Draw 1 card.", udesc="Gain 11 Block. Draw 1 card.",
                         fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(8, 11)), cb.draw(1))),
    "flex": dict(name="Flex", type="SKILL", cost=0,
                 desc="Gain 2 Strength. Lose it at end of turn.",
                 udesc="Gain 4 Strength. Lose it at end of turn.",
                 fx=lambda cb, k, t: (cb.apply(cb.player, "strength", k.v(2, 4)),
                                      cb.apply(cb.player, "flexloss", k.v(2, 4)))),
    "true_grit": dict(name="True Grit", type="SKILL", cost=1,
                      desc="Gain 7 Block. Exhaust a random card in hand.",
                      udesc="Gain 9 Block. Exhaust a card of your choice.",
                      requires=lambda k: "exhaust" if k.upgraded else None,
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(7, 9)),
                                           cb.grit_exhaust(k.upgraded))),
    "bloodletting": dict(name="Bloodletting", type="SKILL", cost=0,
                         desc="Lose 3 HP. Gain 2 Energy.", udesc="Lose 3 HP. Gain 3 Energy.",
                         fx=lambda cb, k, t: (cb.lose_hp(cb.player, 3, from_card=True),
                                              cb.gain_energy(k.v(2, 3)))),
    "armaments": dict(name="Armaments", type="SKILL", cost=1,
                      desc="Gain 5 Block. Upgrade a random card in hand.",
                      udesc="Gain 5 Block. Upgrade ALL cards in hand.",
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, 5),
                                           cb.armaments(k.upgraded))),
    # ── uncommon ──
    "uppercut": dict(name="Uppercut", type="ATTACK", cost=2, targeted=True, rarity="uncommon",
                     desc="Deal 13 damage. Apply 1 Weak. Apply 1 Vulnerable.",
                     udesc="Deal 13 damage. Apply 2 Weak. Apply 2 Vulnerable.",
                     fx=lambda cb, k, t: (cb.player_attack(t, 13),
                                          cb.apply(t, "weak", k.v(1, 2)),
                                          cb.apply(t, "vulnerable", k.v(1, 2)))),
    "heavy_blade": dict(name="Heavy Blade", type="ATTACK", cost=2, targeted=True, rarity="uncommon",
                        desc="Deal 14 damage. Strength affects it 3 times.",
                        udesc="Deal 14 damage. Strength affects it 5 times.",
                        fx=lambda cb, k, t: cb.player_attack(t, 14, str_mult=k.v(3, 5))),
    "whirlwind": dict(name="Whirlwind", type="ATTACK", cost="X", targeted=False, rarity="uncommon",
                      desc="Deal 5 damage to ALL enemies X times.",
                      udesc="Deal 8 damage to ALL enemies X times.",
                      fx=lambda cb, k, t: [cb.player_attack(e, k.v(5, 8))
                                           for _ in range(cb.x_spent) for e in cb.living()]),
    "seeing_red": dict(name="Seeing Red", type="SKILL", cost=1, ucost=0, rarity="uncommon",
                       exhaust=True, desc="Gain 2 Energy. Exhaust.",
                       udesc="Gain 2 Energy. Exhaust.",
                       fx=lambda cb, k, t: cb.gain_energy(2)),
    "offering": dict(name="Offering", type="SKILL", cost=0, rarity="uncommon", exhaust=True,
                     desc="Lose 6 HP. Gain 2 Energy. Draw 3 cards. Exhaust.",
                     udesc="Lose 6 HP. Gain 2 Energy. Draw 5 cards. Exhaust.",
                     fx=lambda cb, k, t: (cb.lose_hp(cb.player, 6, from_card=True),
                                          cb.gain_energy(2), cb.draw(k.v(3, 5)))),
    "second_wind": dict(name="Second Wind", type="SKILL", cost=1, rarity="uncommon",
                        desc="Exhaust all non-Attack cards in hand. Gain 5 Block for each.",
                        udesc="Exhaust all non-Attack cards in hand. Gain 7 Block for each.",
                        fx=lambda cb, k, t: cb.second_wind(k.v(5, 7))),
    "inflame": dict(name="Inflame", type="POWER", cost=1, rarity="uncommon",
                    desc="Gain 2 Strength.", udesc="Gain 3 Strength.",
                    fx=lambda cb, k, t: cb.apply(cb.player, "strength", k.v(2, 3))),
    "metallicize": dict(name="Metallicize", type="POWER", cost=1, rarity="uncommon",
                        desc="At the end of your turn, gain 3 Block.",
                        udesc="At the end of your turn, gain 4 Block.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "metallicize", k.v(3, 4))),
    "feel_no_pain": dict(name="Feel No Pain", type="POWER", cost=1, rarity="uncommon",
                         desc="Whenever a card is Exhausted, gain 3 Block.",
                         udesc="Whenever a card is Exhausted, gain 4 Block.",
                         fx=lambda cb, k, t: cb.apply(cb.player, "feelnopain", k.v(3, 4))),
    "rupture": dict(name="Rupture", type="POWER", cost=1, rarity="uncommon",
                    desc="Whenever you lose HP from a card, gain 1 Strength.",
                    udesc="Whenever you lose HP from a card, gain 2 Strength.",
                    fx=lambda cb, k, t: cb.apply(cb.player, "rupture", k.v(1, 2))),
    "disarm": dict(name="Disarm", type="SKILL", cost=1, targeted=True, rarity="uncommon",
                   exhaust=True, desc="Enemy loses 2 Strength. Exhaust.",
                   udesc="Enemy loses 3 Strength. Exhaust.",
                   fx=lambda cb, k, t: cb.apply(t, "strength", -k.v(2, 3))),
    "shockwave": dict(name="Shockwave", type="SKILL", cost=2, rarity="uncommon", exhaust=True,
                      desc="Apply 3 Weak and 3 Vulnerable to ALL enemies. Exhaust.",
                      udesc="Apply 5 Weak and 5 Vulnerable to ALL enemies. Exhaust.",
                      fx=lambda cb, k, t: [(cb.apply(e, "weak", k.v(3, 5)),
                                            cb.apply(e, "vulnerable", k.v(3, 5)))
                                           for e in cb.living()]),
    "poison_stab": dict(name="Poisoned Stab", type="ATTACK", cost=1, targeted=True,
                        rarity="uncommon", desc="Deal 6 damage. Apply 3 Poison.",
                        udesc="Deal 8 damage. Apply 4 Poison.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(6, 8)),
                                             cb.apply(t, "poison", k.v(3, 4)))),
    "battle_trance": dict(name="Battle Trance", type="SKILL", cost=0, rarity="uncommon",
                          desc="Draw 3 cards. You cannot draw more cards this turn.",
                          udesc="Draw 4 cards. You cannot draw more cards this turn.",
                          fx=lambda cb, k, t: (cb.draw(k.v(3, 4)), cb.lock_draw())),
    # ── rare ──
    "bludgeon": dict(name="Bludgeon", type="ATTACK", cost=3, targeted=True, rarity="rare",
                     desc="Deal 32 damage.", udesc="Deal 42 damage.",
                     fx=lambda cb, k, t: cb.player_attack(t, k.v(32, 42))),
    "reaper": dict(name="Reaper", type="ATTACK", cost=2, rarity="rare", exhaust=True,
                   desc="Deal 4 damage to ALL enemies. Heal HP equal to damage dealt. Exhaust.",
                   udesc="Deal 5 damage to ALL enemies. Heal HP equal to damage dealt. Exhaust.",
                   fx=lambda cb, k, t: cb.reaper(k.v(4, 5))),
    "impervious": dict(name="Impervious", type="SKILL", cost=2, rarity="rare", exhaust=True,
                       desc="Gain 30 Block. Exhaust.", udesc="Gain 40 Block. Exhaust.",
                       fx=lambda cb, k, t: cb.gain_block(cb.player, k.v(30, 40))),
    "demon_form": dict(name="Demon Form", type="POWER", cost=3, rarity="rare",
                       desc="At the start of each turn, gain 2 Strength.",
                       udesc="At the start of each turn, gain 3 Strength.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "demonform", k.v(2, 3))),
    "barricade": dict(name="Barricade", type="POWER", cost=3, ucost=2, rarity="rare",
                      desc="Block is no longer removed at the start of your turn.",
                      udesc="Block is no longer removed at the start of your turn.",
                      fx=lambda cb, k, t: cb.apply(cb.player, "barricade", 1)),
    "juggernaut": dict(name="Juggernaut", type="POWER", cost=2, rarity="rare",
                       desc="Whenever you gain Block, deal 5 damage to a random enemy.",
                       udesc="Whenever you gain Block, deal 7 damage to a random enemy.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "juggernaut", k.v(5, 7))),
    "limit_break": dict(name="Limit Break", type="SKILL", cost=1, rarity="rare", exhaust=True,
                        desc="Double your Strength. Exhaust.", udesc="Double your Strength.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "strength",
                                                     cb.player.s("strength"))),
    # ══ ashwalker ══════════════════════════════════════════════════════════
    # ── starter ──
    "cinder_dart": dict(name="Cinder Dart", type="ATTACK", cost=0, targeted=True,
                        rarity="starter",
                        desc="Deal 4 damage. Apply 1 Weak.",
                        udesc="Deal 6 damage. Apply 2 Weak.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(4, 6)),
                                             cb.apply(t, "weak", k.v(1, 2)))),
    # ── common ──
    "quick_slash": dict(name="Quick Slash", type="ATTACK", cost=1, targeted=True,
                        desc="Deal 8 damage. Draw 1 card.",
                        udesc="Deal 10 damage. Draw 1 card.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 10)), cb.draw(1))),
    "venom_dagger": dict(name="Venom Dagger", type="ATTACK", cost=1, targeted=True,
                         desc="Deal 5 damage. Apply 2 Poison.",
                         udesc="Deal 6 damage. Apply 3 Poison.",
                         fx=lambda cb, k, t: (cb.player_attack(t, k.v(5, 6)),
                                              cb.apply(t, "poison", k.v(2, 3)))),
    "flechettes": dict(name="Flechettes", type="ATTACK", cost=1, targeted=True,
                       desc="Deal 4 damage twice.", udesc="Deal 4 damage three times.",
                       fx=lambda cb, k, t: cb.player_attack(t, 4, times=k.v(2, 3))),
    "sneak_attack": dict(name="Sneak Attack", type="ATTACK", cost=2, targeted=True,
                         desc="Deal 12 damage. Apply 2 Weak.",
                         udesc="Deal 16 damage. Apply 3 Weak.",
                         fx=lambda cb, k, t: (cb.player_attack(t, k.v(12, 16)),
                                              cb.apply(t, "weak", k.v(2, 3)))),
    "slice_and_dice": dict(name="Slice and Dice", type="ATTACK", cost=1,
                           desc="Deal 6 damage to ALL enemies.",
                           udesc="Deal 8 damage to ALL enemies.",
                           fx=lambda cb, k, t: [cb.player_attack(e, k.v(6, 8))
                                                for e in cb.living()]),
    "dodge_roll": dict(name="Dodge Roll", type="SKILL", cost=1,
                       desc="Gain 6 Block. Draw 1 card.", udesc="Gain 9 Block. Draw 1 card.",
                       fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(6, 9)), cb.draw(1))),
    "cloak": dict(name="Cloak of Cinders", type="SKILL", cost=1,
                  desc="Gain 5 Block. Gain 1 Dexterity.",
                  udesc="Gain 7 Block. Gain 1 Dexterity.",
                  fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(5, 7)),
                                       cb.apply(cb.player, "dexterity", 1))),
    "backflip": dict(name="Backflip", type="SKILL", cost=1,
                     desc="Gain 5 Block. Draw 2 cards.", udesc="Gain 8 Block. Draw 2 cards.",
                     fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(5, 8)), cb.draw(2))),
    "acrobatics": dict(name="Acrobatics", type="SKILL", cost=1,
                       desc="Draw 3 cards, then discard 1 card at random.",
                       udesc="Draw 4 cards, then discard 1 card at random.",
                       fx=lambda cb, k, t: (cb.draw(k.v(3, 4)), cb.discard_random(1))),
    "smoke_bomb": dict(name="Smoke Bomb", type="SKILL", cost=1,
                       desc="Apply 2 Weak to ALL enemies.",
                       udesc="Apply 3 Weak to ALL enemies.",
                       fx=lambda cb, k, t: [cb.apply(e, "weak", k.v(2, 3))
                                            for e in cb.living()]),
    "toxic_vial": dict(name="Toxic Vial", type="SKILL", cost=0, targeted=True,
                       desc="Apply 3 Poison.", udesc="Apply 5 Poison.",
                       fx=lambda cb, k, t: cb.apply(t, "poison", k.v(3, 5))),
    # ── uncommon ──
    "deadly_poison": dict(name="Deadly Poison", type="SKILL", cost=1, targeted=True,
                          rarity="uncommon",
                          desc="Apply 6 Poison.", udesc="Apply 9 Poison.",
                          fx=lambda cb, k, t: cb.apply(t, "poison", k.v(6, 9))),
    "blade_dance": dict(name="Blade Dance", type="ATTACK", cost=1, targeted=True,
                        rarity="uncommon",
                        desc="Deal 4 damage three times.", udesc="Deal 4 damage four times.",
                        fx=lambda cb, k, t: cb.player_attack(t, 4, times=k.v(3, 4))),
    "footwork": dict(name="Footwork", type="POWER", cost=1, rarity="uncommon",
                     desc="Gain 2 Dexterity.", udesc="Gain 3 Dexterity.",
                     fx=lambda cb, k, t: cb.apply(cb.player, "dexterity", k.v(2, 3))),
    "crippling_cloud": dict(name="Crippling Cloud", type="SKILL", cost=2, rarity="uncommon",
                            exhaust=True,
                            desc="Apply 4 Poison and 2 Weak to ALL enemies. Exhaust.",
                            udesc="Apply 7 Poison and 2 Weak to ALL enemies. Exhaust.",
                            fx=lambda cb, k, t: [(cb.apply(e, "poison", k.v(4, 7)),
                                                  cb.apply(e, "weak", 2))
                                                 for e in cb.living()]),
    "well_laid_plans": dict(name="Well-Laid Plans", type="SKILL", cost=1, rarity="uncommon",
                            desc="Gain 8 Block. Gain 1 Dexterity.",
                            udesc="Gain 11 Block. Gain 2 Dexterity.",
                            fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(8, 11)),
                                                 cb.apply(cb.player, "dexterity", k.v(1, 2)))),
    "catalyst": dict(name="Catalyst", type="SKILL", cost=2, ucost=1, targeted=True,
                     rarity="uncommon", exhaust=True,
                     desc="Double an enemy's Poison. Exhaust.",
                     udesc="Triple an enemy's Poison. Exhaust.",
                     fx=lambda cb, k, t: cb.multiply_poison(t, k.v(2, 3))),
    "dagger_spray": dict(name="Dagger Spray", type="ATTACK", cost=1, rarity="uncommon",
                         desc="Deal 4 damage to ALL enemies twice.",
                         udesc="Deal 6 damage to ALL enemies twice.",
                         fx=lambda cb, k, t: [cb.player_attack(e, k.v(4, 6))
                                              for _ in range(2) for e in cb.living()]),
    "escape_plan": dict(name="Escape Plan", type="SKILL", cost=0, rarity="uncommon",
                        desc="Draw 1 card. Gain 3 Block.", udesc="Draw 1 card. Gain 5 Block.",
                        fx=lambda cb, k, t: (cb.draw(1),
                                             cb.gain_block(cb.player, k.v(3, 5)))),
    "bane": dict(name="Bane", type="ATTACK", cost=1, targeted=True, rarity="uncommon",
                 desc="Deal 7 damage. Deal 7 more if the target is Poisoned.",
                 udesc="Deal 10 damage. Deal 10 more if the target is Poisoned.",
                 fx=lambda cb, k, t: cb.bane(t, k.v(7, 10))),
    "nightmare_toxin": dict(name="Nightmare Toxin", type="SKILL", cost=1, targeted=True,
                            rarity="uncommon",
                            desc="Apply 3 Poison and 2 Vulnerable.",
                            udesc="Apply 4 Poison and 3 Vulnerable.",
                            fx=lambda cb, k, t: (cb.apply(t, "poison", k.v(3, 4)),
                                                 cb.apply(t, "vulnerable", k.v(2, 3)))),
    "flying_knee": dict(name="Flying Knee", type="ATTACK", cost=1, targeted=True,
                        rarity="uncommon",
                        desc="Deal 8 damage. Gain 1 Energy next turn.",
                        udesc="Deal 11 damage. Gain 1 Energy next turn.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 11)),
                                             cb.energy_next_turn(1))),
    # ── rare ──
    "bouncing_flask": dict(name="Bouncing Flask", type="SKILL", cost=2, rarity="rare",
                           desc="Apply 3 Poison to a random enemy 3 times.",
                           udesc="Apply 3 Poison to a random enemy 4 times.",
                           fx=lambda cb, k, t: cb.bounce_poison(3, k.v(3, 4))),
    "venom_bloom": dict(name="Venom Bloom", type="POWER", cost=2, rarity="rare",
                        desc="At the start of each turn, apply 2 Poison to ALL enemies.",
                        udesc="At the start of each turn, apply 3 Poison to ALL enemies.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "venombloom", k.v(2, 3))),
    "after_image": dict(name="After Image", type="POWER", cost=1, rarity="rare",
                        desc="Whenever you play a card, gain 1 Block.",
                        udesc="Whenever you play a card, gain 2 Block.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "afterimage", k.v(1, 2))),
    "a_thousand_cuts": dict(name="A Thousand Cuts", type="POWER", cost=2, rarity="rare",
                            desc="Whenever you play a card, deal 1 damage to ALL enemies.",
                            udesc="Whenever you play a card, deal 2 damage to ALL enemies.",
                            fx=lambda cb, k, t: cb.apply(cb.player, "thousandcuts", k.v(1, 2))),
    "envenom": dict(name="Envenom", type="POWER", cost=2, ucost=1, rarity="rare",
                    desc="Whenever an attack deals unblocked damage, apply 1 Poison.",
                    udesc="Whenever an attack deals unblocked damage, apply 2 Poison.",
                    fx=lambda cb, k, t: cb.apply(cb.player, "envenom", k.v(1, 2))),
    "grand_finale": dict(name="Grand Finale", type="ATTACK", cost=3, rarity="rare",
                         exhaust=True,
                         desc="Deal 20 damage to ALL enemies. Exhaust.",
                         udesc="Deal 26 damage to ALL enemies. Exhaust.",
                         fx=lambda cb, k, t: [cb.player_attack(e, k.v(20, 26))
                                              for e in cb.living()]),
    # ── statuses & curses ──
    "wound": dict(name="Wound", type="STATUS", cost=0, playable=False, upgradable=False,
                  rarity="none", desc="Unplayable."),
    "burn": dict(name="Burn", type="STATUS", cost=0, playable=False, upgradable=False,
                 rarity="none", desc="Unplayable. At the end of your turn, take 2 damage."),
    "slimed": dict(name="Slimed", type="STATUS", cost=1, upgradable=False, rarity="none",
                   exhaust=True, desc="Exhaust.", fx=lambda cb, k, t: None),
    "regret": dict(name="Regret", type="CURSE", cost=0, playable=False, upgradable=False,
                   rarity="none", desc="Unplayable. At the end of your turn, lose 1 HP "
                                       "per card in your hand."),

    # ── sentinel ──
    "ember_shield": dict(name="Ember Shield", type="SKILL", cost=1,
                         desc="Gain 4 Block. Gain 1 Thorns.",
                         udesc="Gain 6 Block. Gain 2 Thorns.",
                         fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(4, 6)),
                                              cb.apply(cb.player, "thorns", k.v(1, 2)))),
    "crushing_blow": dict(name="Crushing Blow", type="ATTACK", cost=2, targeted=True,
                          rarity="uncommon",
                          desc="Deal 14 damage. Apply 2 Weak.",
                          udesc="Deal 18 damage. Apply 3 Weak.",
                          fx=lambda cb, k, t: (cb.player_attack(t, k.v(14, 18)),
                                               cb.apply(t, "weak", k.v(2, 3)))),
    "unyielding": dict(name="Unyielding", type="POWER", cost=2, rarity="rare",
                       desc="Gain 3 Metallicize and 2 Dexterity.",
                       udesc="Gain 4 Metallicize and 3 Dexterity.",
                       fx=lambda cb, k, t: (cb.apply(cb.player, "metallicize", k.v(3, 4)),
                                            cb.apply(cb.player, "dexterity", k.v(2, 3)))),

    # ── ashwalker ──
    "caltrops": dict(name="Caltrops", type="SKILL", cost=1,
                     desc="Gain 3 Thorns.", udesc="Gain 5 Thorns.",
                     fx=lambda cb, k, t: cb.apply(cb.player, "thorns", k.v(3, 5))),
    "vial_toss": dict(name="Vial Toss", type="ATTACK", cost=1, targeted=True,
                      rarity="uncommon",
                      desc="Deal 5 damage. Apply 3 Poison.",
                      udesc="Deal 7 damage. Apply 4 Poison.",
                      fx=lambda cb, k, t: (cb.player_attack(t, k.v(5, 7)),
                                           cb.apply(t, "poison", k.v(3, 4)))),
    "shadowstep": dict(name="Shadowstep", type="SKILL", cost=1, rarity="rare",
                       exhaust=True,
                       desc="Draw 3 cards. Gain 2 Energy. Exhaust.",
                       udesc="Draw 4 cards. Gain 2 Energy. Exhaust.",
                       fx=lambda cb, k, t: (cb.draw(k.v(3, 4)), cb.gain_energy(2))),
}
