"""Card definitions.

Each entry is pure data plus an `fx(combat, card, target)` callable. `card.v(a, b)`
picks the base or upgraded value. Optional keys: `ucost`, `rarity`, `exhaust`,
`targeted`, `playable`, `upgradable`, `udesc`, `requires`.

`requires` names an extra choice the player must supply alongside the play action
(currently only "exhaust", for True Grit). The engine never prompts for it — the
client sends it with the action.
"""

CARDS = {
    # ── starter ──
    "strike": dict(name="Strike", type="ATTACK", cost=1, targeted=True, rarity="starter",
                   desc="Deal 6 damage.", udesc="Deal 9 damage.",
                   fx=lambda cb, k, t: cb.player_attack(t, k.v(6, 9))),
    "defend": dict(name="Defend", type="SKILL", cost=1, rarity="starter",
                   desc="Gain 5 Block.", udesc="Gain 8 Block.",
                   fx=lambda cb, k, t: cb.gain_block(cb.player, k.v(5, 8))),
    "bash": dict(name="Bash", type="ATTACK", cost=2, targeted=True, rarity="starter",
                 desc="Deal 8 damage. Apply 2 Vulnerable.",
                 udesc="Deal 10 damage. Apply 3 Vulnerable.",
                 fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 10)),
                                      cb.apply(t, "vulnerable", k.v(2, 3)))),
    # ── common ──
    "cleave": dict(name="Cleave", type="ATTACK", cost=1,
                   desc="Deal 8 damage to ALL enemies.", udesc="Deal 11 damage to ALL enemies.",
                   fx=lambda cb, k, t: [cb.player_attack(e, k.v(8, 11)) for e in cb.living()]),
    "twin_strike": dict(name="Twin Strike", type="ATTACK", cost=1, targeted=True,
                        desc="Deal 5 damage twice.", udesc="Deal 7 damage twice.",
                        fx=lambda cb, k, t: cb.player_attack(t, k.v(5, 7), times=2)),
    "pommel_strike": dict(name="Pommel Strike", type="ATTACK", cost=1, targeted=True,
                          desc="Deal 9 damage. Draw 1 card.",
                          udesc="Deal 10 damage. Draw 2 cards.",
                          fx=lambda cb, k, t: (cb.player_attack(t, k.v(9, 10)),
                                               cb.draw(k.v(1, 2)))),
    "iron_wave": dict(name="Iron Wave", type="ATTACK", cost=1, targeted=True,
                      desc="Gain 5 Block. Deal 5 damage.", udesc="Gain 7 Block. Deal 7 damage.",
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(5, 7)),
                                           cb.player_attack(t, k.v(5, 7)))),
    "clothesline": dict(name="Clothesline", type="ATTACK", cost=2, targeted=True,
                        desc="Deal 12 damage. Apply 2 Weak.",
                        udesc="Deal 14 damage. Apply 3 Weak.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(12, 14)),
                                             cb.apply(t, "weak", k.v(2, 3)))),
    "body_slam": dict(name="Body Slam", type="ATTACK", cost=1, ucost=0, targeted=True,
                      desc="Deal damage equal to your Block.",
                      udesc="Deal damage equal to your Block.",
                      fx=lambda cb, k, t: cb.player_attack(t, cb.player.block)),
    "shrug_it_off": dict(name="Shrug It Off", type="SKILL", cost=1,
                         desc="Gain 8 Block. Draw 1 card.", udesc="Gain 11 Block. Draw 1 card.",
                         fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(8, 11)), cb.draw(1))),
    "flex": dict(name="Flex", type="SKILL", cost=0,
                 desc="Gain 2 Strength. Lose it at end of turn.",
                 udesc="Gain 4 Strength. Lose it at end of turn.",
                 fx=lambda cb, k, t: (cb.apply(cb.player, "strength", k.v(2, 4)),
                                      cb.apply(cb.player, "flexloss", k.v(2, 4)))),
    "true_grit": dict(name="True Grit", type="SKILL", cost=1,
                      desc="Gain 7 Block. Exhaust a random card in hand.",
                      udesc="Gain 9 Block. Exhaust a card of your choice.",
                      requires=lambda k: "exhaust" if k.upgraded else None,
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(7, 9)),
                                           cb.grit_exhaust(k.upgraded))),
    "bloodletting": dict(name="Bloodletting", type="SKILL", cost=0,
                         desc="Lose 3 HP. Gain 2 Energy.", udesc="Lose 3 HP. Gain 3 Energy.",
                         fx=lambda cb, k, t: (cb.lose_hp(cb.player, 3, from_card=True),
                                              cb.gain_energy(k.v(2, 3)))),
    "armaments": dict(name="Armaments", type="SKILL", cost=1,
                      desc="Gain 5 Block. Upgrade a random card in hand.",
                      udesc="Gain 5 Block. Upgrade ALL cards in hand.",
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, 5),
                                           cb.armaments(k.upgraded))),
    # ── uncommon ──
    "uppercut": dict(name="Uppercut", type="ATTACK", cost=2, targeted=True, rarity="uncommon",
                     desc="Deal 13 damage. Apply 1 Weak. Apply 1 Vulnerable.",
                     udesc="Deal 13 damage. Apply 2 Weak. Apply 2 Vulnerable.",
                     fx=lambda cb, k, t: (cb.player_attack(t, 13),
                                          cb.apply(t, "weak", k.v(1, 2)),
                                          cb.apply(t, "vulnerable", k.v(1, 2)))),
    "heavy_blade": dict(name="Heavy Blade", type="ATTACK", cost=2, targeted=True, rarity="uncommon",
                        desc="Deal 14 damage. Strength affects it 3 times.",
                        udesc="Deal 14 damage. Strength affects it 5 times.",
                        fx=lambda cb, k, t: cb.player_attack(t, 14, str_mult=k.v(3, 5))),
    "whirlwind": dict(name="Whirlwind", type="ATTACK", cost="X", targeted=False, rarity="uncommon",
                      desc="Deal 5 damage to ALL enemies X times.",
                      udesc="Deal 8 damage to ALL enemies X times.",
                      fx=lambda cb, k, t: [cb.player_attack(e, k.v(5, 8))
                                           for _ in range(cb.x_spent) for e in cb.living()]),
    "seeing_red": dict(name="Seeing Red", type="SKILL", cost=1, ucost=0, rarity="uncommon",
                       exhaust=True, desc="Gain 2 Energy. Exhaust.",
                       udesc="Gain 2 Energy. Exhaust.",
                       fx=lambda cb, k, t: cb.gain_energy(2)),
    "offering": dict(name="Offering", type="SKILL", cost=0, rarity="uncommon", exhaust=True,
                     desc="Lose 6 HP. Gain 2 Energy. Draw 3 cards. Exhaust.",
                     udesc="Lose 6 HP. Gain 2 Energy. Draw 5 cards. Exhaust.",
                     fx=lambda cb, k, t: (cb.lose_hp(cb.player, 6, from_card=True),
                                          cb.gain_energy(2), cb.draw(k.v(3, 5)))),
    "second_wind": dict(name="Second Wind", type="SKILL", cost=1, rarity="uncommon",
                        desc="Exhaust all non-Attack cards in hand. Gain 5 Block for each.",
                        udesc="Exhaust all non-Attack cards in hand. Gain 7 Block for each.",
                        fx=lambda cb, k, t: cb.second_wind(k.v(5, 7))),
    "inflame": dict(name="Inflame", type="POWER", cost=1, rarity="uncommon",
                    desc="Gain 2 Strength.", udesc="Gain 3 Strength.",
                    fx=lambda cb, k, t: cb.apply(cb.player, "strength", k.v(2, 3))),
    "metallicize": dict(name="Metallicize", type="POWER", cost=1, rarity="uncommon",
                        desc="At the end of your turn, gain 3 Block.",
                        udesc="At the end of your turn, gain 4 Block.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "metallicize", k.v(3, 4))),
    "feel_no_pain": dict(name="Feel No Pain", type="POWER", cost=1, rarity="uncommon",
                         desc="Whenever a card is Exhausted, gain 3 Block.",
                         udesc="Whenever a card is Exhausted, gain 4 Block.",
                         fx=lambda cb, k, t: cb.apply(cb.player, "feelnopain", k.v(3, 4))),
    "rupture": dict(name="Rupture", type="POWER", cost=1, rarity="uncommon",
                    desc="Whenever you lose HP from a card, gain 1 Strength.",
                    udesc="Whenever you lose HP from a card, gain 2 Strength.",
                    fx=lambda cb, k, t: cb.apply(cb.player, "rupture", k.v(1, 2))),
    "disarm": dict(name="Disarm", type="SKILL", cost=1, targeted=True, rarity="uncommon",
                   exhaust=True, desc="Enemy loses 2 Strength. Exhaust.",
                   udesc="Enemy loses 3 Strength. Exhaust.",
                   fx=lambda cb, k, t: cb.apply(t, "strength", -k.v(2, 3))),
    "shockwave": dict(name="Shockwave", type="SKILL", cost=2, rarity="uncommon", exhaust=True,
                      desc="Apply 3 Weak and 3 Vulnerable to ALL enemies. Exhaust.",
                      udesc="Apply 5 Weak and 5 Vulnerable to ALL enemies. Exhaust.",
                      fx=lambda cb, k, t: [(cb.apply(e, "weak", k.v(3, 5)),
                                            cb.apply(e, "vulnerable", k.v(3, 5)))
                                           for e in cb.living()]),
    "poison_stab": dict(name="Poisoned Stab", type="ATTACK", cost=1, targeted=True,
                        rarity="uncommon", desc="Deal 6 damage. Apply 3 Poison.",
                        udesc="Deal 8 damage. Apply 4 Poison.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(6, 8)),
                                             cb.apply(t, "poison", k.v(3, 4)))),
    "battle_trance": dict(name="Battle Trance", type="SKILL", cost=0, rarity="uncommon",
                          desc="Draw 3 cards. You cannot draw more cards this turn.",
                          udesc="Draw 4 cards. You cannot draw more cards this turn.",
                          fx=lambda cb, k, t: (cb.draw(k.v(3, 4)), cb.lock_draw())),
    # ── rare ──
    "bludgeon": dict(name="Bludgeon", type="ATTACK", cost=3, targeted=True, rarity="rare",
                     desc="Deal 32 damage.", udesc="Deal 42 damage.",
                     fx=lambda cb, k, t: cb.player_attack(t, k.v(32, 42))),
    "reaper": dict(name="Reaper", type="ATTACK", cost=2, rarity="rare", exhaust=True,
                   desc="Deal 4 damage to ALL enemies. Heal HP equal to damage dealt. Exhaust.",
                   udesc="Deal 5 damage to ALL enemies. Heal HP equal to damage dealt. Exhaust.",
                   fx=lambda cb, k, t: cb.reaper(k.v(4, 5))),
    "impervious": dict(name="Impervious", type="SKILL", cost=2, rarity="rare", exhaust=True,
                       desc="Gain 30 Block. Exhaust.", udesc="Gain 40 Block. Exhaust.",
                       fx=lambda cb, k, t: cb.gain_block(cb.player, k.v(30, 40))),
    "demon_form": dict(name="Demon Form", type="POWER", cost=3, rarity="rare",
                       desc="At the start of each turn, gain 2 Strength.",
                       udesc="At the start of each turn, gain 3 Strength.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "demonform", k.v(2, 3))),
    "barricade": dict(name="Barricade", type="POWER", cost=3, ucost=2, rarity="rare",
                      desc="Block is no longer removed at the start of your turn.",
                      udesc="Block is no longer removed at the start of your turn.",
                      fx=lambda cb, k, t: cb.apply(cb.player, "barricade", 1)),
    "juggernaut": dict(name="Juggernaut", type="POWER", cost=2, rarity="rare",
                       desc="Whenever you gain Block, deal 5 damage to a random enemy.",
                       udesc="Whenever you gain Block, deal 7 damage to a random enemy.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "juggernaut", k.v(5, 7))),
    "limit_break": dict(name="Limit Break", type="SKILL", cost=1, rarity="rare", exhaust=True,
                        desc="Double your Strength. Exhaust.", udesc="Double your Strength.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "strength",
                                                     cb.player.s("strength"))),
    # ══ ashwalker ══════════════════════════════════════════════════════════
    # ── starter ──
    "cinder_dart": dict(name="Cinder Dart", type="ATTACK", cost=0, targeted=True,
                        rarity="starter",
                        desc="Deal 4 damage. Apply 1 Weak.",
                        udesc="Deal 6 damage. Apply 2 Weak.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(4, 6)),
                                             cb.apply(t, "weak", k.v(1, 2)))),
    # ── common ──
    "quick_slash": dict(name="Quick Slash", type="ATTACK", cost=1, targeted=True,
                        desc="Deal 8 damage. Draw 1 card.",
                        udesc="Deal 10 damage. Draw 1 card.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 10)), cb.draw(1))),
    "venom_dagger": dict(name="Venom Dagger", type="ATTACK", cost=1, targeted=True,
                         desc="Deal 5 damage. Apply 2 Poison.",
                         udesc="Deal 6 damage. Apply 3 Poison.",
                         fx=lambda cb, k, t: (cb.player_attack(t, k.v(5, 6)),
                                              cb.apply(t, "poison", k.v(2, 3)))),
    "flechettes": dict(name="Flechettes", type="ATTACK", cost=1, targeted=True,
                       desc="Deal 4 damage twice.", udesc="Deal 4 damage three times.",
                       fx=lambda cb, k, t: cb.player_attack(t, 4, times=k.v(2, 3))),
    "sneak_attack": dict(name="Sneak Attack", type="ATTACK", cost=2, targeted=True,
                         desc="Deal 12 damage. Apply 2 Weak.",
                         udesc="Deal 16 damage. Apply 3 Weak.",
                         fx=lambda cb, k, t: (cb.player_attack(t, k.v(12, 16)),
                                              cb.apply(t, "weak", k.v(2, 3)))),
    "slice_and_dice": dict(name="Slice and Dice", type="ATTACK", cost=1,
                           desc="Deal 6 damage to ALL enemies.",
                           udesc="Deal 8 damage to ALL enemies.",
                           fx=lambda cb, k, t: [cb.player_attack(e, k.v(6, 8))
                                                for e in cb.living()]),
    "dodge_roll": dict(name="Dodge Roll", type="SKILL", cost=1,
                       desc="Gain 6 Block. Draw 1 card.", udesc="Gain 9 Block. Draw 1 card.",
                       fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(6, 9)), cb.draw(1))),
    "cloak": dict(name="Cloak of Cinders", type="SKILL", cost=1,
                  desc="Gain 5 Block. Gain 1 Dexterity.",
                  udesc="Gain 7 Block. Gain 1 Dexterity.",
                  fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(5, 7)),
                                       cb.apply(cb.player, "dexterity", 1))),
    "backflip": dict(name="Backflip", type="SKILL", cost=1,
                     desc="Gain 5 Block. Draw 2 cards.", udesc="Gain 8 Block. Draw 2 cards.",
                     fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(5, 8)), cb.draw(2))),
    "acrobatics": dict(name="Acrobatics", type="SKILL", cost=1,
                       desc="Draw 3 cards, then discard 1 card at random.",
                       udesc="Draw 4 cards, then discard 1 card at random.",
                       fx=lambda cb, k, t: (cb.draw(k.v(3, 4)), cb.discard_random(1))),
    "smoke_bomb": dict(name="Smoke Bomb", type="SKILL", cost=1,
                       desc="Apply 2 Weak to ALL enemies.",
                       udesc="Apply 3 Weak to ALL enemies.",
                       fx=lambda cb, k, t: [cb.apply(e, "weak", k.v(2, 3))
                                            for e in cb.living()]),
    "toxic_vial": dict(name="Toxic Vial", type="SKILL", cost=0, targeted=True,
                       desc="Apply 3 Poison.", udesc="Apply 5 Poison.",
                       fx=lambda cb, k, t: cb.apply(t, "poison", k.v(3, 5))),
    # ── uncommon ──
    "deadly_poison": dict(name="Deadly Poison", type="SKILL", cost=1, targeted=True,
                          rarity="uncommon",
                          desc="Apply 6 Poison.", udesc="Apply 9 Poison.",
                          fx=lambda cb, k, t: cb.apply(t, "poison", k.v(6, 9))),
    "blade_dance": dict(name="Blade Dance", type="ATTACK", cost=1, targeted=True,
                        rarity="uncommon",
                        desc="Deal 4 damage three times.", udesc="Deal 4 damage four times.",
                        fx=lambda cb, k, t: cb.player_attack(t, 4, times=k.v(3, 4))),
    "footwork": dict(name="Footwork", type="POWER", cost=1, rarity="uncommon",
                     desc="Gain 2 Dexterity.", udesc="Gain 3 Dexterity.",
                     fx=lambda cb, k, t: cb.apply(cb.player, "dexterity", k.v(2, 3))),
    "crippling_cloud": dict(name="Crippling Cloud", type="SKILL", cost=2, rarity="uncommon",
                            exhaust=True,
                            desc="Apply 4 Poison and 2 Weak to ALL enemies. Exhaust.",
                            udesc="Apply 7 Poison and 2 Weak to ALL enemies. Exhaust.",
                            fx=lambda cb, k, t: [(cb.apply(e, "poison", k.v(4, 7)),
                                                  cb.apply(e, "weak", 2))
                                                 for e in cb.living()]),
    "well_laid_plans": dict(name="Well-Laid Plans", type="SKILL", cost=1, rarity="uncommon",
                            desc="Gain 8 Block. Gain 1 Dexterity.",
                            udesc="Gain 11 Block. Gain 2 Dexterity.",
                            fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(8, 11)),
                                                 cb.apply(cb.player, "dexterity", k.v(1, 2)))),
    "catalyst": dict(name="Catalyst", type="SKILL", cost=2, ucost=1, targeted=True,
                     rarity="uncommon", exhaust=True,
                     desc="Double an enemy's Poison. Exhaust.",
                     udesc="Triple an enemy's Poison. Exhaust.",
                     fx=lambda cb, k, t: cb.multiply_poison(t, k.v(2, 3))),
    "dagger_spray": dict(name="Dagger Spray", type="ATTACK", cost=1, rarity="uncommon",
                         desc="Deal 4 damage to ALL enemies twice.",
                         udesc="Deal 6 damage to ALL enemies twice.",
                         fx=lambda cb, k, t: [cb.player_attack(e, k.v(4, 6))
                                              for _ in range(2) for e in cb.living()]),
    "escape_plan": dict(name="Escape Plan", type="SKILL", cost=0, rarity="uncommon",
                        desc="Draw 1 card. Gain 3 Block.", udesc="Draw 1 card. Gain 5 Block.",
                        fx=lambda cb, k, t: (cb.draw(1),
                                             cb.gain_block(cb.player, k.v(3, 5)))),
    "bane": dict(name="Bane", type="ATTACK", cost=1, targeted=True, rarity="uncommon",
                 desc="Deal 7 damage. Deal 7 more if the target is Poisoned.",
                 udesc="Deal 10 damage. Deal 10 more if the target is Poisoned.",
                 fx=lambda cb, k, t: cb.bane(t, k.v(7, 10))),
    "nightmare_toxin": dict(name="Nightmare Toxin", type="SKILL", cost=1, targeted=True,
                            rarity="uncommon",
                            desc="Apply 3 Poison and 2 Vulnerable.",
                            udesc="Apply 4 Poison and 3 Vulnerable.",
                            fx=lambda cb, k, t: (cb.apply(t, "poison", k.v(3, 4)),
                                                 cb.apply(t, "vulnerable", k.v(2, 3)))),
    "flying_knee": dict(name="Flying Knee", type="ATTACK", cost=1, targeted=True,
                        rarity="uncommon",
                        desc="Deal 8 damage. Gain 1 Energy next turn.",
                        udesc="Deal 11 damage. Gain 1 Energy next turn.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 11)),
                                             cb.energy_next_turn(1))),
    # ── rare ──
    "bouncing_flask": dict(name="Bouncing Flask", type="SKILL", cost=2, rarity="rare",
                           desc="Apply 3 Poison to a random enemy 3 times.",
                           udesc="Apply 3 Poison to a random enemy 4 times.",
                           fx=lambda cb, k, t: cb.bounce_poison(3, k.v(3, 4))),
    "venom_bloom": dict(name="Venom Bloom", type="POWER", cost=2, rarity="rare",
                        desc="At the start of each turn, apply 2 Poison to ALL enemies.",
                        udesc="At the start of each turn, apply 3 Poison to ALL enemies.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "venombloom", k.v(2, 3))),
    "after_image": dict(name="After Image", type="POWER", cost=1, rarity="rare",
                        desc="Whenever you play a card, gain 1 Block.",
                        udesc="Whenever you play a card, gain 2 Block.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "afterimage", k.v(1, 2))),
    "a_thousand_cuts": dict(name="A Thousand Cuts", type="POWER", cost=2, rarity="rare",
                            desc="Whenever you play a card, deal 1 damage to ALL enemies.",
                            udesc="Whenever you play a card, deal 2 damage to ALL enemies.",
                            fx=lambda cb, k, t: cb.apply(cb.player, "thousandcuts", k.v(1, 2))),
    "envenom": dict(name="Envenom", type="POWER", cost=2, ucost=1, rarity="rare",
                    desc="Whenever an attack deals unblocked damage, apply 1 Poison.",
                    udesc="Whenever an attack deals unblocked damage, apply 2 Poison.",
                    fx=lambda cb, k, t: cb.apply(cb.player, "envenom", k.v(1, 2))),
    "grand_finale": dict(name="Grand Finale", type="ATTACK", cost=3, rarity="rare",
                         exhaust=True,
                         desc="Deal 20 damage to ALL enemies. Exhaust.",
                         udesc="Deal 26 damage to ALL enemies. Exhaust.",
                         fx=lambda cb, k, t: [cb.player_attack(e, k.v(20, 26))
                                              for e in cb.living()]),
    # ── statuses & curses ──
    "wound": dict(name="Wound", type="STATUS", cost=0, playable=False, upgradable=False,
                  rarity="none", desc="Unplayable."),
    "burn": dict(name="Burn", type="STATUS", cost=0, playable=False, upgradable=False,
                 rarity="none", desc="Unplayable. At the end of your turn, take 2 damage."),
    "slimed": dict(name="Slimed", type="STATUS", cost=1, upgradable=False, rarity="none",
                   exhaust=True, desc="Exhaust.", fx=lambda cb, k, t: None),
    "regret": dict(name="Regret", type="CURSE", cost=0, playable=False, upgradable=False,
                   rarity="none", desc="Unplayable. At the end of your turn, lose 1 HP "
                                       "per card in your hand."),

    # ── sentinel ──
    "ember_shield": dict(name="Ember Shield", type="SKILL", cost=1,
                         desc="Gain 4 Block. Gain 1 Thorns.",
                         udesc="Gain 6 Block. Gain 2 Thorns.",
                         fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(4, 6)),
                                              cb.apply(cb.player, "thorns", k.v(1, 2)))),
    "crushing_blow": dict(name="Crushing Blow", type="ATTACK", cost=2, targeted=True,
                          rarity="uncommon",
                          desc="Deal 14 damage. Apply 2 Weak.",
                          udesc="Deal 18 damage. Apply 3 Weak.",
                          fx=lambda cb, k, t: (cb.player_attack(t, k.v(14, 18)),
                                               cb.apply(t, "weak", k.v(2, 3)))),
    "unyielding": dict(name="Unyielding", type="POWER", cost=2, rarity="rare",
                       desc="Gain 3 Metallicize and 2 Dexterity.",
                       udesc="Gain 4 Metallicize and 3 Dexterity.",
                       fx=lambda cb, k, t: (cb.apply(cb.player, "metallicize", k.v(3, 4)),
                                            cb.apply(cb.player, "dexterity", k.v(2, 3)))),

    # ── ashwalker ──
    "caltrops": dict(name="Caltrops", type="SKILL", cost=1,
                     desc="Gain 3 Thorns.", udesc="Gain 5 Thorns.",
                     fx=lambda cb, k, t: cb.apply(cb.player, "thorns", k.v(3, 5))),
    "vial_toss": dict(name="Vial Toss", type="ATTACK", cost=1, targeted=True,
                      rarity="uncommon",
                      desc="Deal 5 damage. Apply 3 Poison.",
                      udesc="Deal 7 damage. Apply 4 Poison.",
                      fx=lambda cb, k, t: (cb.player_attack(t, k.v(5, 7)),
                                           cb.apply(t, "poison", k.v(3, 4)))),
    "shadowstep": dict(name="Shadowstep", type="SKILL", cost=1, rarity="rare",
                       exhaust=True,
                       desc="Draw 3 cards. Gain 2 Energy. Exhaust.",
                       udesc="Draw 4 cards. Gain 2 Energy. Exhaust.",
                       fx=lambda cb, k, t: (cb.draw(k.v(3, 4)), cb.gain_energy(2))),

    # ══ stormbound ═════════════════════════════════════════════════════════
    # ── starter ──
    "static_lash": dict(name="Static Lash", type="ATTACK", cost=1, targeted=True,
                        rarity="starter",
                        desc="Deal 5 damage. Gain 1 Coil.",
                        udesc="Deal 7 damage. Gain 1 Coil.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(5, 7)),
                                             cb.channel("stormcoil", 1))),
    # ── common ──
    "charge_bolt": dict(name="Charge Bolt", type="ATTACK", cost=1, targeted=True,
                        desc="Deal 7 damage. Gain 1 Coil.",
                        udesc="Deal 10 damage. Gain 1 Coil.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(7, 10)),
                                             cb.channel("stormcoil", 1))),
    "rimeshard": dict(name="Rimeshard", type="SKILL", cost=1,
                      desc="Gain 4 Block. Gain 1 Frost.",
                      udesc="Gain 6 Block. Gain 1 Frost.",
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(4, 6)),
                                           cb.channel("frostward", 1))),
    "coil_up": dict(name="Coil Up", type="SKILL", cost=1,
                    desc="Gain 2 Coil.", udesc="Gain 3 Coil.",
                    fx=lambda cb, k, t: cb.channel("stormcoil", k.v(2, 3))),
    "lightning_lance": dict(name="Lightning Lance", type="ATTACK", cost=1, targeted=True,
                            desc="Deal 8 damage. Deal 4 more if you hold any Coil.",
                            udesc="Deal 11 damage. Deal 5 more if you hold any Coil.",
                            fx=lambda cb, k, t: cb.player_attack(
                                t, k.v(8, 11) + (k.v(4, 5) if cb.player.s("stormcoil") else 0))),
    "hailstone": dict(name="Hailstone", type="ATTACK", cost=1,
                      desc="Deal 5 damage to ALL enemies.",
                      udesc="Deal 7 damage to ALL enemies.",
                      fx=lambda cb, k, t: [cb.player_attack(e, k.v(5, 7))
                                           for e in cb.living()]),
    "spark_shower": dict(name="Spark Shower", type="ATTACK", cost=1,
                         desc="Deal 3 damage to ALL enemies twice.",
                         udesc="Deal 4 damage to ALL enemies twice.",
                         fx=lambda cb, k, t: [cb.player_attack(e, k.v(3, 4))
                                              for _ in range(2) for e in cb.living()]),
    "overclock": dict(name="Overclock", type="SKILL", cost=0,
                      desc="Draw 2 cards. Add a Burn to your discard pile.",
                      udesc="Draw 3 cards. Add a Burn to your discard pile.",
                      fx=lambda cb, k, t: (cb.draw(k.v(2, 3)),
                                           cb.add_new_card("burn"))),
    "capacitor": dict(name="Capacitor", type="SKILL", cost=1,
                      desc="Gain 1 Coil and 1 Frost.",
                      udesc="Gain 2 Coil and 1 Frost.",
                      fx=lambda cb, k, t: (cb.channel("stormcoil", k.v(1, 2)),
                                           cb.channel("frostward", 1))),
    "arc_weld": dict(name="Arc Weld", type="ATTACK", cost=1, targeted=True,
                     desc="Deal 6 damage. Gain 4 Block.",
                     udesc="Deal 8 damage. Gain 6 Block.",
                     fx=lambda cb, k, t: (cb.player_attack(t, k.v(6, 8)),
                                          cb.gain_block(cb.player, k.v(4, 6)))),
    "cold_snap": dict(name="Cold Snap", type="SKILL", cost=1,
                      desc="Gain 5 Block. Apply 1 Weak to ALL enemies.",
                      udesc="Gain 7 Block. Apply 2 Weak to ALL enemies.",
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(5, 7)),
                                           [cb.apply(e, "weak", k.v(1, 2))
                                            for e in cb.living()])),
    "recharge": dict(name="Recharge", type="SKILL", cost=0,
                     desc="Gain 1 Coil. Draw 1 card.",
                     udesc="Gain 2 Coil. Draw 1 card.",
                     fx=lambda cb, k, t: (cb.channel("stormcoil", k.v(1, 2)), cb.draw(1))),
    "hull_plating": dict(name="Hull Plating", type="SKILL", cost=1,
                         desc="Gain 6 Block. Gain 3 more if you hold any Frost.",
                         udesc="Gain 8 Block. Gain 4 more if you hold any Frost.",
                         fx=lambda cb, k, t: cb.gain_block(
                             cb.player,
                             k.v(6, 8) + (k.v(3, 4) if cb.player.s("frostward") else 0))),
    # ── uncommon ──
    "focus_lens": dict(name="Focus Lens", type="POWER", cost=1, rarity="uncommon",
                       desc="Gain 1 Focus.", udesc="Gain 2 Focus.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "focus", k.v(1, 2))),
    "thunderstrike": dict(name="Thunderstrike", type="ATTACK", cost=2, targeted=True,
                          rarity="uncommon",
                          desc="Deal 12 damage. Gain 2 Coil.",
                          udesc="Deal 16 damage. Gain 2 Coil.",
                          fx=lambda cb, k, t: (cb.player_attack(t, k.v(12, 16)),
                                               cb.channel("stormcoil", 2))),
    "blizzard": dict(name="Blizzard", type="SKILL", cost=2, rarity="uncommon",
                     desc="Gain 3 Frost.", udesc="Gain 4 Frost.",
                     fx=lambda cb, k, t: cb.channel("frostward", k.v(3, 4))),
    "overload": dict(name="Overload", type="ATTACK", cost=1, targeted=True,
                     rarity="uncommon",
                     desc="Consume all Coil. Deal 5 damage per Coil consumed.",
                     udesc="Consume all Coil. Deal 7 damage per Coil consumed.",
                     fx=lambda cb, k, t: cb.discharge_coils(k.v(5, 7), t)),
    "chain_lightning": dict(name="Chain Lightning", type="ATTACK", cost=2,
                            rarity="uncommon",
                            desc="Deal 6 damage to a random enemy 3 times.",
                            udesc="Deal 6 damage to a random enemy 4 times.",
                            fx=lambda cb, k, t: [cb.player_attack(cb.rng.choice(cb.living()), 6)
                                                 for _ in range(k.v(3, 4)) if cb.living()]),
    "glacier": dict(name="Glacier", type="SKILL", cost=2, rarity="uncommon",
                    desc="Gain 12 Block. Gain 1 Frost.",
                    udesc="Gain 16 Block. Gain 2 Frost.",
                    fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(12, 16)),
                                         cb.channel("frostward", k.v(1, 2)))),
    "reroute": dict(name="Reroute", type="SKILL", cost=0, rarity="uncommon",
                    desc="Lose 3 HP. Gain 1 Coil and 1 Energy.",
                    udesc="Lose 3 HP. Gain 2 Coil and 1 Energy.",
                    fx=lambda cb, k, t: (cb.lose_hp(cb.player, 3, from_card=True),
                                         cb.channel("stormcoil", k.v(1, 2)),
                                         cb.gain_energy(1))),
    "storm_engine": dict(name="Storm Engine", type="POWER", cost=2, rarity="uncommon",
                         desc="At the start of each turn, gain 1 Coil.",
                         udesc="At the start of each turn, gain 2 Coil.",
                         fx=lambda cb, k, t: cb.apply(cb.player, "dynamo", k.v(1, 2))),
    "sleet_volley": dict(name="Sleet Volley", type="ATTACK", cost=1, rarity="uncommon",
                         desc="Deal 4 damage to ALL enemies. Gain 1 Frost.",
                         udesc="Deal 6 damage to ALL enemies. Gain 1 Frost.",
                         fx=lambda cb, k, t: ([cb.player_attack(e, k.v(4, 6))
                                               for e in cb.living()],
                                              cb.channel("frostward", 1))),
    "conductor": dict(name="Conductor", type="POWER", cost=1, rarity="uncommon",
                      desc="Whenever you play a Skill, gain 1 Coil.",
                      udesc="Whenever you play a Skill, gain 2 Coil.",
                      fx=lambda cb, k, t: cb.apply(cb.player, "conductor", k.v(1, 2))),
    # ── rare ──
    "echo_form": dict(name="Echo Form", type="POWER", cost=3, rarity="rare",
                      desc="The first card you play each turn is played twice.",
                      udesc="The first card you play each turn is played twice.",
                      ucost=2,
                      fx=lambda cb, k, t: cb.apply(cb.player, "echoform", 1)),
    "tempest_crown": dict(name="Tempest Crown", type="POWER", cost=2, rarity="rare",
                          desc="Gain 2 Focus.", udesc="Gain 3 Focus.",
                          fx=lambda cb, k, t: cb.apply(cb.player, "focus", k.v(2, 3))),
    "cataclysm": dict(name="Cataclysm", type="ATTACK", cost=2, rarity="rare", exhaust=True,
                      desc="Deal 14 damage to ALL enemies. Gain 3 Coil. Exhaust.",
                      udesc="Deal 18 damage to ALL enemies. Gain 3 Coil. Exhaust.",
                      fx=lambda cb, k, t: ([cb.player_attack(e, k.v(14, 18))
                                            for e in cb.living()],
                                           cb.channel("stormcoil", 3))),
    "rime_bastion": dict(name="Rime Bastion", type="POWER", cost=2, rarity="rare",
                         desc="Gain 3 Frost and 1 Focus.",
                         udesc="Gain 4 Frost and 1 Focus.",
                         fx=lambda cb, k, t: (cb.channel("frostward", k.v(3, 4)),
                                              cb.apply(cb.player, "focus", 1))),
    "feedback_loop": dict(name="Feedback Loop", type="SKILL", cost=1, ucost=0,
                          rarity="rare", exhaust=True,
                          desc="Double your Focus. Exhaust.",
                          udesc="Double your Focus. Exhaust.",
                          fx=lambda cb, k, t: cb.apply(cb.player, "focus",
                                                       cb.player.s("focus"))),
    "singularity": dict(name="Singularity", type="ATTACK", cost=3, rarity="rare",
                        desc="Consume all Coil. Deal 8 damage per Coil to ALL enemies.",
                        udesc="Consume all Coil. Deal 11 damage per Coil to ALL enemies.",
                        fx=lambda cb, k, t: cb.discharge_coils(k.v(8, 11))),
    "lightning_rod": dict(name="Lightning Rod", type="POWER", cost=2, rarity="rare",
                          desc="Whenever you gain Block, gain 1 Coil.",
                          udesc="Whenever you gain Block, gain 2 Coil.",
                          fx=lambda cb, k, t: cb.apply(cb.player, "lightningrod", k.v(1, 2))),

    # ══ penitent ═══════════════════════════════════════════════════════════
    # ── starter ──
    "ember_kata": dict(name="Ember Kata", type="ATTACK", cost=1, targeted=True,
                       rarity="starter",
                       desc="Deal 8 damage. Enter Wrath.",
                       udesc="Deal 10 damage. Enter Wrath.",
                       fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 10)),
                                            cb.enter_stance("wrath"))),
    "still_flame": dict(name="Still Flame", type="SKILL", cost=1, rarity="starter",
                        desc="Gain 8 Block. Enter Calm.",
                        udesc="Gain 11 Block. Enter Calm.",
                        fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(8, 11)),
                                             cb.enter_stance("calm"))),
    "insight": dict(name="Insight", type="SKILL", cost=0, rarity="none", exhaust=True,
                    desc="Draw 2 cards. Exhaust.", udesc="Draw 3 cards. Exhaust.",
                    fx=lambda cb, k, t: cb.draw(k.v(2, 3))),
    # ── common ──
    "crescendo": dict(name="Crescendo", type="SKILL", cost=1, ucost=0, exhaust=True,
                      desc="Enter Wrath. Exhaust.", udesc="Enter Wrath. Exhaust.",
                      fx=lambda cb, k, t: cb.enter_stance("wrath")),
    "tranquility": dict(name="Tranquility", type="SKILL", cost=1, ucost=0, exhaust=True,
                        desc="Enter Calm. Exhaust.", udesc="Enter Calm. Exhaust.",
                        fx=lambda cb, k, t: cb.enter_stance("calm")),
    "empty_fist": dict(name="Empty Fist", type="ATTACK", cost=1, targeted=True,
                       desc="Deal 9 damage. Leave your stance.",
                       udesc="Deal 12 damage. Leave your stance.",
                       fx=lambda cb, k, t: (cb.player_attack(t, k.v(9, 12)),
                                            cb.enter_stance(None))),
    "empty_body": dict(name="Empty Body", type="SKILL", cost=1,
                       desc="Gain 7 Block. Leave your stance.",
                       udesc="Gain 10 Block. Leave your stance.",
                       fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(7, 10)),
                                            cb.enter_stance(None))),
    "flurry_of_ash": dict(name="Flurry of Ash", type="ATTACK", cost=1, targeted=True,
                          desc="Deal 4 damage twice.", udesc="Deal 5 damage twice.",
                          fx=lambda cb, k, t: cb.player_attack(t, k.v(4, 5), times=2)),
    "prostrate": dict(name="Prostrate", type="SKILL", cost=0,
                      desc="Gain 3 Block. Gain 2 Mantra.",
                      udesc="Gain 4 Block. Gain 3 Mantra.",
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(3, 4)),
                                           cb.gain_mantra(k.v(2, 3)))),
    "evaluate": dict(name="Evaluate", type="SKILL", cost=1,
                     desc="Gain 6 Block. Shuffle an Insight into your draw pile.",
                     udesc="Gain 9 Block. Shuffle an Insight into your draw pile.",
                     fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(6, 9)),
                                          cb.add_new_card("insight", to_draw=True))),
    "halt": dict(name="Halt", type="SKILL", cost=0,
                 desc="Gain 3 Block. Gain 6 more if you are in Wrath.",
                 udesc="Gain 4 Block. Gain 9 more if you are in Wrath.",
                 fx=lambda cb, k, t: cb.gain_block(
                     cb.player, k.v(3, 4) + (k.v(6, 9) if cb.player.s("wrath") else 0))),
    "sash_whip": dict(name="Sash Whip", type="ATTACK", cost=1, targeted=True,
                      desc="Deal 8 damage. Apply 1 Weak.",
                      udesc="Deal 10 damage. Apply 2 Weak.",
                      fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 10)),
                                           cb.apply(t, "weak", k.v(1, 2)))),
    "cut_through_fate": dict(name="Cut Through Fate", type="ATTACK", cost=1, targeted=True,
                             desc="Deal 7 damage. Draw 1 card. Gain 1 Mantra.",
                             udesc="Deal 9 damage. Draw 1 card. Gain 2 Mantra.",
                             fx=lambda cb, k, t: (cb.player_attack(t, k.v(7, 9)),
                                                  cb.draw(1), cb.gain_mantra(k.v(1, 2)))),
    "crush_joints": dict(name="Crush Joints", type="ATTACK", cost=1, targeted=True,
                         desc="Deal 8 damage. Apply 1 Vulnerable.",
                         udesc="Deal 10 damage. Apply 2 Vulnerable.",
                         fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 10)),
                                              cb.apply(t, "vulnerable", k.v(1, 2)))),
    "third_eye": dict(name="Third Eye", type="SKILL", cost=1,
                      desc="Gain 7 Block. Gain 2 Mantra.",
                      udesc="Gain 10 Block. Gain 3 Mantra.",
                      fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(7, 10)),
                                           cb.gain_mantra(k.v(2, 3)))),
    # ── uncommon ──
    "wreath_of_flame": dict(name="Wreath of Flame", type="SKILL", cost=1, rarity="uncommon",
                            desc="Gain 5 Vigour.", udesc="Gain 8 Vigour.",
                            fx=lambda cb, k, t: cb.apply(cb.player, "vigour", k.v(5, 8))),
    "battle_hymn": dict(name="Battle Hymn", type="POWER", cost=1, rarity="uncommon",
                        desc="At the start of each turn, gain 1 Mantra.",
                        udesc="At the start of each turn, gain 2 Mantra.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "devotion", k.v(1, 2))),
    "fear_no_evil": dict(name="Fear No Evil", type="ATTACK", cost=1, targeted=True,
                         rarity="uncommon",
                         desc="Deal 8 damage. If the enemy intends to attack, enter Calm.",
                         udesc="Deal 11 damage. If the enemy intends to attack, enter Calm.",
                         fx=lambda cb, k, t: (cb.player_attack(t, k.v(8, 11)),
                                              cb.enter_stance("calm")
                                              if t and t.intent
                                              and t.moves[t.intent]["kind"] == "attack"
                                              else None)),
    "mental_fortress": dict(name="Mental Fortress", type="POWER", cost=1, rarity="uncommon",
                            desc="Whenever you change stance, gain 4 Block.",
                            udesc="Whenever you change stance, gain 6 Block.",
                            fx=lambda cb, k, t: cb.apply(cb.player, "mentalfortress",
                                                         k.v(4, 6))),
    "rushdown": dict(name="Rushdown", type="POWER", cost=1, ucost=0, rarity="uncommon",
                     desc="Whenever you enter Wrath, draw 2 cards.",
                     udesc="Whenever you enter Wrath, draw 2 cards.",
                     fx=lambda cb, k, t: cb.apply(cb.player, "rushdown", 2)),
    "wallop": dict(name="Wallop", type="ATTACK", cost=2, targeted=True, rarity="uncommon",
                   desc="Deal 11 damage. Gain Block equal to the HP it takes.",
                   udesc="Deal 14 damage. Gain Block equal to the HP it takes.",
                   fx=lambda cb, k, t: cb.wallop(t, k.v(11, 14))),
    "windmill_strike": dict(name="Windmill Strike", type="ATTACK", cost=2, targeted=True,
                            rarity="uncommon",
                            desc="Deal 12 damage. Gain 3 Vigour.",
                            udesc="Deal 16 damage. Gain 4 Vigour.",
                            fx=lambda cb, k, t: (cb.player_attack(t, k.v(12, 16)),
                                                 cb.apply(cb.player, "vigour", k.v(3, 4)))),
    "fasting": dict(name="Fasting", type="POWER", cost=2, rarity="uncommon",
                    desc="Gain 3 Strength and 3 Dexterity. "
                         "Start each turn with 1 less Energy.",
                    udesc="Gain 4 Strength and 4 Dexterity. "
                          "Start each turn with 1 less Energy.",
                    fx=lambda cb, k, t: (cb.apply(cb.player, "strength", k.v(3, 4)),
                                         cb.apply(cb.player, "dexterity", k.v(3, 4)),
                                         cb.apply(cb.player, "fasting", 1))),
    "inner_peace": dict(name="Inner Peace", type="SKILL", cost=1, rarity="uncommon",
                        desc="If you are in Calm, draw 3 cards. Otherwise enter Calm.",
                        udesc="If you are in Calm, draw 4 cards. Otherwise enter Calm.",
                        fx=lambda cb, k, t: (cb.draw(k.v(3, 4)) if cb.player.s("calm")
                                             else cb.enter_stance("calm"))),
    "sanctity": dict(name="Sanctity", type="SKILL", cost=1, rarity="uncommon",
                     desc="Gain 6 Block. If the last card played was a Skill, draw 2 cards.",
                     udesc="Gain 9 Block. If the last card played was a Skill, draw 2 cards.",
                     fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(6, 9)),
                                          cb.draw(2) if cb.last_played_type == "SKILL"
                                          else None)),
    "worship": dict(name="Worship", type="SKILL", cost=2, ucost=1, rarity="uncommon",
                    desc="Gain 5 Mantra.", udesc="Gain 5 Mantra.",
                    fx=lambda cb, k, t: cb.gain_mantra(5)),
    "pray": dict(name="Pray", type="SKILL", cost=1, rarity="uncommon", exhaust=True,
                 desc="Gain 3 Mantra. Shuffle an Insight into your draw pile. Exhaust.",
                 udesc="Gain 4 Mantra. Shuffle an Insight into your draw pile. Exhaust.",
                 fx=lambda cb, k, t: (cb.gain_mantra(k.v(3, 4)),
                                      cb.add_new_card("insight", to_draw=True))),
    # ── rare ──
    "blasphemy": dict(name="Blasphemy", type="SKILL", cost=1, ucost=0, rarity="rare",
                      exhaust=True,
                      desc="Enter Divinity. Exhaust.", udesc="Enter Divinity. Exhaust.",
                      fx=lambda cb, k, t: cb.enter_stance("divinity")),
    "abiding_flame": dict(name="Abiding Flame", type="POWER", cost=2, rarity="rare",
                          desc="At the start of each turn, gain 3 Mantra.",
                          udesc="At the start of each turn, gain 4 Mantra.",
                          fx=lambda cb, k, t: cb.apply(cb.player, "devotion", k.v(3, 4))),
    "lesson_learned": dict(name="Lesson Learned", type="ATTACK", cost=2, targeted=True,
                           rarity="rare", exhaust=True,
                           desc="Deal 10 damage. If this kills, permanently upgrade a "
                                "card in your deck. Exhaust.",
                           udesc="Deal 13 damage. If this kills, permanently upgrade a "
                                 "card in your deck. Exhaust.",
                           fx=lambda cb, k, t: cb.lesson_learned(t, k.v(10, 13))),
    "ragnarok": dict(name="Ragnarok", type="ATTACK", cost=3, rarity="rare",
                     desc="Deal 5 damage to a random enemy 5 times.",
                     udesc="Deal 6 damage to a random enemy 6 times.",
                     fx=lambda cb, k, t: [cb.player_attack(cb.rng.choice(cb.living()),
                                                           k.v(5, 6))
                                          for _ in range(k.v(5, 6)) if cb.living()]),
    "spirit_shield": dict(name="Spirit Shield", type="SKILL", cost=2, rarity="rare",
                          desc="Gain 3 Block for each card in your hand.",
                          udesc="Gain 4 Block for each card in your hand.",
                          fx=lambda cb, k, t: cb.gain_block(cb.player,
                                                            k.v(3, 4) * len(cb.hand))),
    "judgment": dict(name="Judgment", type="SKILL", cost=1, targeted=True, rarity="rare",
                     desc="If the enemy has 30 HP or less, it dies.",
                     udesc="If the enemy has 40 HP or less, it dies.",
                     fx=lambda cb, k, t: cb.judgment(t, k.v(30, 40))),
    "master_reality": dict(name="Master Reality", type="POWER", cost=1, ucost=0,
                           rarity="rare",
                           desc="Cards created during combat arrive upgraded.",
                           udesc="Cards created during combat arrive upgraded.",
                           fx=lambda cb, k, t: cb.apply(cb.player, "masterreality", 1)),

    # ══ gravewright ════════════════════════════════════════════════════════
    # ── starter ──
    "grave_touch": dict(name="Grave Touch", type="ATTACK", cost=1, targeted=True,
                        rarity="starter",
                        desc="Deal 7 damage. Exhaust the top card of your draw pile.",
                        udesc="Deal 9 damage. Exhaust the top card of your draw pile.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(7, 9)), cb.mill(1))),
    # ── common ──
    "pyre": dict(name="Pyre", type="ATTACK", cost=1,
                 desc="Exhaust every Status and Curse in your hand. "
                      "Deal 5 damage to ALL enemies for each.",
                 udesc="Exhaust every Status and Curse in your hand. "
                       "Deal 7 damage to ALL enemies for each.",
                 fx=lambda cb, k, t: cb.pyre(k.v(5, 7))),
    "sever_ties": dict(name="Sever Ties", type="SKILL", cost=1,
                       desc="Exhaust a card at random from your hand. Draw 2 cards.",
                       udesc="Exhaust a card at random from your hand. Draw 3 cards.",
                       fx=lambda cb, k, t: (cb.grit_exhaust(False), cb.draw(k.v(2, 3)))),
    "ash_scatter": dict(name="Ash Scatter", type="ATTACK", cost=1,
                        desc="Deal 5 damage to ALL enemies. "
                             "Exhaust the top card of your draw pile.",
                        udesc="Deal 7 damage to ALL enemies. "
                              "Exhaust the top card of your draw pile.",
                        fx=lambda cb, k, t: ([cb.player_attack(e, k.v(5, 7))
                                              for e in cb.living()], cb.mill(1))),
    "grave_dust": dict(name="Grave Dust", type="SKILL", cost=1,
                       desc="Gain 6 Block. Exhaust the top card of your draw pile.",
                       udesc="Gain 9 Block. Exhaust the top card of your draw pile.",
                       fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(6, 9)),
                                            cb.mill(1))),
    "reclaim": dict(name="Reclaim", type="SKILL", cost=1,
                    desc="Return a random exhausted card to your hand.",
                    udesc="Return 2 random exhausted cards to your hand.",
                    fx=lambda cb, k, t: cb.reclaim(k.v(1, 2))),
    "dead_weight": dict(name="Dead Weight", type="SKILL", cost=0,
                        desc="Exhaust a card at random from your hand. Gain 1 Energy.",
                        udesc="Exhaust a card of your choice. Gain 1 Energy.",
                        requires=lambda k: "exhaust" if k.upgraded else None,
                        fx=lambda cb, k, t: (cb.grit_exhaust(k.upgraded),
                                             cb.gain_energy(1))),
    "soul_tap": dict(name="Soul Tap", type="SKILL", cost=0,
                     desc="Lose 4 HP. Draw 2 cards.", udesc="Lose 3 HP. Draw 2 cards.",
                     fx=lambda cb, k, t: (cb.lose_hp(cb.player, k.v(4, 3), from_card=True),
                                          cb.draw(2))),
    "mourning_veil": dict(name="Mourning Veil", type="SKILL", cost=1,
                          desc="Gain 9 Block. Lose 2 HP.",
                          udesc="Gain 12 Block. Lose 2 HP.",
                          fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(9, 12)),
                                               cb.lose_hp(cb.player, 2, from_card=True))),
    "necrotic_slash": dict(name="Necrotic Slash", type="ATTACK", cost=1, targeted=True,
                           desc="Deal 9 damage. Lose 2 HP.",
                           udesc="Deal 12 damage. Lose 2 HP.",
                           fx=lambda cb, k, t: (cb.player_attack(t, k.v(9, 12)),
                                                cb.lose_hp(cb.player, 2, from_card=True))),
    "hollow_call": dict(name="Hollow Call", type="SKILL", cost=1,
                        desc="Draw 2 cards. Add a Wound to your discard pile.",
                        udesc="Draw 3 cards. Add a Wound to your discard pile.",
                        fx=lambda cb, k, t: (cb.draw(k.v(2, 3)),
                                             cb.add_new_card("wound"))),
    "cairn_guard": dict(name="Cairn Guard", type="SKILL", cost=1,
                        desc="Gain 6 Block. Gain 3 more if a card has burned this combat.",
                        udesc="Gain 8 Block. Gain 4 more if a card has burned this combat.",
                        fx=lambda cb, k, t: cb.gain_block(
                            cb.player,
                            k.v(6, 8) + (k.v(3, 4) if cb.exhausts_this_combat else 0))),
    # ── uncommon ──
    "ashen_embrace": dict(name="Ashen Embrace", type="POWER", cost=2, ucost=1,
                          rarity="uncommon",
                          desc="Whenever a card is Exhausted, draw 1 card.",
                          udesc="Whenever a card is Exhausted, draw 1 card.",
                          fx=lambda cb, k, t: cb.apply(cb.player, "ashenembrace", 1)),
    "soulfire_rite": dict(name="Soulfire Rite", type="POWER", cost=1, rarity="uncommon",
                          desc="Whenever a card is Exhausted, deal 3 damage to ALL enemies.",
                          udesc="Whenever a card is Exhausted, deal 4 damage to ALL enemies.",
                          fx=lambda cb, k, t: cb.apply(cb.player, "soulfire", k.v(3, 4))),
    "corpse_harvest": dict(name="Corpse Harvest", type="ATTACK", cost=2, rarity="uncommon",
                           exhaust=True,
                           desc="Deal 10 damage to ALL enemies. Heal 3 HP for each enemy "
                                "slain this combat. Exhaust.",
                           udesc="Deal 14 damage to ALL enemies. Heal 3 HP for each enemy "
                                 "slain this combat. Exhaust.",
                           fx=lambda cb, k, t: ([cb.player_attack(e, k.v(10, 14))
                                                 for e in cb.living()],
                                                cb.heal(cb.player, 3 * cb.kills))),
    "boneyard": dict(name="Boneyard", type="SKILL", cost=1, rarity="uncommon",
                     desc="Exhaust the top 3 cards of your draw pile. Gain 3 Block for each.",
                     udesc="Exhaust the top 3 cards of your draw pile. Gain 5 Block for each.",
                     fx=lambda cb, k, t: cb.boneyard(3, k.v(3, 5))),
    "grim_bargain": dict(name="Grim Bargain", type="SKILL", cost=1, rarity="uncommon",
                         desc="Gain 3 Strength. Add 2 Wounds to your draw pile.",
                         udesc="Gain 4 Strength. Add 1 Wound to your draw pile.",
                         fx=lambda cb, k, t: (cb.apply(cb.player, "strength", k.v(3, 4)),
                                              cb.add_new_card("wound", n=k.v(2, 1),
                                                              to_draw=True))),
    "exhume": dict(name="Exhume", type="SKILL", cost=1, rarity="uncommon", exhaust=True,
                   desc="Return 2 random exhausted cards to your hand. Exhaust.",
                   udesc="Return 3 random exhausted cards to your hand. Exhaust.",
                   fx=lambda cb, k, t: cb.reclaim(k.v(2, 3))),
    "deathknell": dict(name="Deathknell", type="ATTACK", cost=2, targeted=True,
                       rarity="uncommon",
                       desc="Deal 11 damage. If this kills, gain 2 Energy and draw 2 cards.",
                       udesc="Deal 15 damage. If this kills, gain 2 Energy and draw 2 cards.",
                       fx=lambda cb, k, t: (cb.player_attack(t, k.v(11, 15)),
                                            (cb.gain_energy(2), cb.draw(2))
                                            if t and not t.alive else None)),
    "funeral_rites": dict(name="Funeral Rites", type="SKILL", cost=2, rarity="uncommon",
                          desc="Exhaust your hand. Gain 3 Block and draw 1 card for each.",
                          udesc="Exhaust your hand. Gain 4 Block and draw 1 card for each.",
                          fx=lambda cb, k, t: cb.funeral_rites(k.v(3, 4))),
    # ── rare ──
    "soul_forge": dict(name="Soul Forge", type="POWER", cost=2, rarity="rare",
                       desc="Whenever a card is Exhausted, gain 1 Strength.",
                       udesc="Whenever a card is Exhausted, gain 2 Strength.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "soulforge", k.v(1, 2))),
    "cremation": dict(name="Cremation", type="ATTACK", cost=3, rarity="rare", exhaust=True,
                      desc="Exhaust your hand. Deal 8 damage to ALL enemies for each "
                           "card burned. Exhaust.",
                      udesc="Exhaust your hand. Deal 10 damage to ALL enemies for each "
                            "card burned. Exhaust.",
                      fx=lambda cb, k, t: cb.cremate(k.v(8, 10))),
    "lich_crown": dict(name="Lich Crown", type="POWER", cost=2, rarity="rare",
                       desc="At the start of each turn, exhaust the top card of your "
                            "draw pile.",
                       udesc="At the start of each turn, exhaust the top 2 cards of your "
                             "draw pile.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "lichcrown", k.v(1, 2))),
    "phylactery": dict(name="Phylactery", type="POWER", cost=2, rarity="rare",
                       desc="The next blow that would kill you leaves you at 25 HP instead.",
                       udesc="The next two blows that would kill you leave you at 25 HP "
                             "instead.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "phylactery", k.v(1, 2))),
    "grave_tide": dict(name="Grave Tide", type="ATTACK", cost=2, rarity="rare",
                       desc="Deal damage to ALL enemies equal to twice the cards burned "
                            "this combat.",
                       udesc="Deal damage to ALL enemies equal to three times the cards "
                             "burned this combat.",
                       fx=lambda cb, k, t: [cb.player_attack(e, k.v(2, 3)
                                                             * cb.exhausts_this_combat)
                                            for e in cb.living()]),
    "wake_the_ash": dict(name="Wake the Ash", type="SKILL", cost=2, ucost=1, rarity="rare",
                         exhaust=True,
                         desc="Shuffle every exhausted card back into your draw pile. "
                              "Exhaust.",
                         udesc="Shuffle every exhausted card back into your draw pile. "
                               "Exhaust.",
                         fx=lambda cb, k, t: cb.wake_the_ash()),

    # ══ emberbrewer ════════════════════════════════════════════════════════
    # ── starter ──
    "quick_brew": dict(name="Quick Brew", type="SKILL", cost=1, rarity="starter",
                       desc="Brew a random potion.",
                       udesc="Brew a random potion. Draw 1 card.",
                       fx=lambda cb, k, t: (cb.brew(), cb.draw(1) if k.upgraded else None)),
    # ── common ──
    "firebomb": dict(name="Firebomb", type="ATTACK", cost=2,
                     desc="Deal 10 damage to ALL enemies.",
                     udesc="Deal 14 damage to ALL enemies.",
                     fx=lambda cb, k, t: [cb.player_attack(e, k.v(10, 14))
                                          for e in cb.living()]),
    "bitter_draught": dict(name="Bitter Draught", type="SKILL", cost=0,
                           desc="Lose 3 HP. Brew a random potion.",
                           udesc="Lose 2 HP. Brew a random potion.",
                           fx=lambda cb, k, t: (cb.lose_hp(cb.player, k.v(3, 2),
                                                           from_card=True), cb.brew())),
    "beaker_shield": dict(name="Beaker Shield", type="SKILL", cost=1,
                          desc="Gain 6 Block. Gain 3 more if you carry a potion.",
                          udesc="Gain 8 Block. Gain 4 more if you carry a potion.",
                          fx=lambda cb, k, t: cb.gain_block(
                              cb.player,
                              k.v(6, 8) + (k.v(3, 4) if cb.player.potions else 0))),
    "acid_flask": dict(name="Acid Flask", type="ATTACK", cost=1, targeted=True,
                       desc="Deal 5 damage. Apply 2 Vulnerable.",
                       udesc="Deal 7 damage. Apply 3 Vulnerable.",
                       fx=lambda cb, k, t: (cb.player_attack(t, k.v(5, 7)),
                                            cb.apply(t, "vulnerable", k.v(2, 3)))),
    "emberglass": dict(name="Emberglass", type="ATTACK", cost=1, targeted=True,
                       desc="Deal 10 damage. Lose 2 HP.",
                       udesc="Deal 13 damage. Lose 2 HP.",
                       fx=lambda cb, k, t: (cb.player_attack(t, k.v(10, 13)),
                                            cb.lose_hp(cb.player, 2, from_card=True))),
    "decant": dict(name="Decant", type="SKILL", cost=1,
                   desc="Brew a Block Potion.",
                   udesc="Brew a Block Potion. Gain 4 Block.",
                   fx=lambda cb, k, t: (cb.brew("block"),
                                        cb.gain_block(cb.player, 4) if k.upgraded
                                        else None)),
    "distil": dict(name="Distil", type="SKILL", cost=1,
                   desc="Exhaust a card at random from your hand. Brew a random potion.",
                   udesc="Exhaust a card of your choice. Brew a random potion.",
                   requires=lambda k: "exhaust" if k.upgraded else None,
                   fx=lambda cb, k, t: (cb.grit_exhaust(k.upgraded), cb.brew())),
    "spill": dict(name="Spill", type="ATTACK", cost=0,
                  desc="Deal 4 damage to ALL enemies.",
                  udesc="Deal 6 damage to ALL enemies.",
                  fx=lambda cb, k, t: [cb.player_attack(e, k.v(4, 6))
                                       for e in cb.living()]),
    "tonic": dict(name="Tonic", type="SKILL", cost=1,
                  desc="Heal 4 HP. Gain 5 Block.", udesc="Heal 6 HP. Gain 7 Block.",
                  fx=lambda cb, k, t: (cb.heal(cb.player, k.v(4, 6)),
                                       cb.gain_block(cb.player, k.v(5, 7)))),
    "sample": dict(name="Sample", type="SKILL", cost=1,
                   desc="Draw 2 cards. Lose 1 HP.", udesc="Draw 3 cards. Lose 1 HP.",
                   fx=lambda cb, k, t: (cb.draw(k.v(2, 3)),
                                        cb.lose_hp(cb.player, 1, from_card=True))),
    # ── uncommon ──
    "volatile_mix": dict(name="Volatile Mix", type="POWER", cost=1, rarity="uncommon",
                         desc="Whenever you drink a potion, deal 8 damage to ALL enemies.",
                         udesc="Whenever you drink a potion, deal 12 damage to ALL enemies.",
                         fx=lambda cb, k, t: cb.apply(cb.player, "volatility", k.v(8, 12))),
    "elixir_ward": dict(name="Elixir Ward", type="POWER", cost=1, rarity="uncommon",
                        desc="Whenever you drink a potion, gain 8 Block.",
                        udesc="Whenever you drink a potion, gain 12 Block.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "elixirward", k.v(8, 12))),
    "alchemize": dict(name="Alchemize", type="SKILL", cost=1, ucost=0, rarity="uncommon",
                      exhaust=True,
                      desc="Brew a random potion. Exhaust.",
                      udesc="Brew a random potion. Exhaust.",
                      fx=lambda cb, k, t: cb.brew()),
    "fire_oil": dict(name="Fire Oil", type="ATTACK", cost=1, targeted=True,
                     rarity="uncommon",
                     desc="Deal 7 damage. Deal 7 more if you carry a potion.",
                     udesc="Deal 9 damage. Deal 9 more if you carry a potion.",
                     fx=lambda cb, k, t: cb.player_attack(
                         t, k.v(7, 9) * (2 if cb.player.potions else 1))),
    "unstable_compound": dict(name="Unstable Compound", type="ATTACK", cost=2,
                              rarity="uncommon",
                              desc="Deal 6 damage to ALL enemies twice. Lose 3 HP.",
                              udesc="Deal 8 damage to ALL enemies twice. Lose 3 HP.",
                              fx=lambda cb, k, t: ([cb.player_attack(e, k.v(6, 8))
                                                    for _ in range(2)
                                                    for e in cb.living()],
                                                   cb.lose_hp(cb.player, 3,
                                                              from_card=True))),
    "panacea": dict(name="Panacea", type="SKILL", cost=1, rarity="uncommon",
                    desc="Heal 8 HP. Shed your Weak, Vulnerable and Frail.",
                    udesc="Heal 12 HP. Shed your Weak, Vulnerable and Frail.",
                    fx=lambda cb, k, t: (cb.heal(cb.player, k.v(8, 12)), cb.cleanse())),
    "flash_powder": dict(name="Flash Powder", type="SKILL", cost=1, rarity="uncommon",
                         desc="Apply 2 Weak to ALL enemies. Gain 4 Block.",
                         udesc="Apply 3 Weak to ALL enemies. Gain 6 Block.",
                         fx=lambda cb, k, t: ([cb.apply(e, "weak", k.v(2, 3))
                                               for e in cb.living()],
                                              cb.gain_block(cb.player, k.v(4, 6)))),
    "siphon": dict(name="Siphon", type="ATTACK", cost=2, targeted=True, rarity="uncommon",
                   desc="Deal 12 damage. Heal 5 HP.", udesc="Deal 15 damage. Heal 7 HP.",
                   fx=lambda cb, k, t: (cb.player_attack(t, k.v(12, 15)),
                                        cb.heal(cb.player, k.v(5, 7)))),
    "potion_belt": dict(name="Potion Belt", type="SKILL", cost=1, rarity="uncommon",
                        exhaust=True,
                        desc="Raise your potion slots by 1. Brew a random potion. Exhaust.",
                        udesc="Raise your potion slots by 2. Brew a random potion. Exhaust.",
                        fx=lambda cb, k, t: (cb.widen_belt(k.v(1, 2)), cb.brew())),
    "double_brew": dict(name="Double Brew", type="SKILL", cost=2, ucost=1,
                        rarity="uncommon",
                        desc="Brew 2 random potions.", udesc="Brew 2 random potions.",
                        fx=lambda cb, k, t: cb.brew(n=2)),
    # ── rare ──
    "grand_elixir": dict(name="Grand Elixir", type="SKILL", cost=2, ucost=1, rarity="rare",
                         exhaust=True,
                         desc="Brew 3 random potions. Exhaust.",
                         udesc="Brew 3 random potions. Exhaust.",
                         fx=lambda cb, k, t: cb.brew(n=3)),
    "philosophers_stone": dict(name="Philosopher's Stone", type="POWER", cost=2, ucost=1,
                               rarity="rare",
                               desc="Gain 1 Energy at the start of each turn. "
                                    "ALL enemies gain 1 Strength.",
                               udesc="Gain 1 Energy at the start of each turn. "
                                     "ALL enemies gain 1 Strength.",
                               fx=lambda cb, k, t: (cb.apply(cb.player, "philosopher", 1),
                                                    [cb.apply(e, "strength", 1)
                                                     for e in cb.living()])),
    "firestorm": dict(name="Firestorm", type="ATTACK", cost=2, rarity="rare",
                      desc="Deal 12 damage to ALL enemies. Brew a Fire Potion.",
                      udesc="Deal 16 damage to ALL enemies. Brew a Fire Potion.",
                      fx=lambda cb, k, t: ([cb.player_attack(e, k.v(12, 16))
                                            for e in cb.living()], cb.brew("fire"))),
    "potency": dict(name="Potency", type="POWER", cost=2, ucost=1, rarity="rare",
                    desc="Your potions take effect twice.",
                    udesc="Your potions take effect twice.",
                    fx=lambda cb, k, t: cb.apply(cb.player, "potency", 1)),
    "alchemical_heart": dict(name="Alchemical Heart", type="POWER", cost=2, rarity="rare",
                             desc="At the start of each turn, brew a random potion.",
                             udesc="At the start of each turn, brew 2 random potions.",
                             fx=lambda cb, k, t: cb.apply(cb.player, "alchemicalheart",
                                                          k.v(1, 2))),
    "overdose": dict(name="Overdose", type="ATTACK", cost=2, rarity="rare", exhaust=True,
                     desc="Deal 8 damage to ALL enemies for each potion you carry. Exhaust.",
                     udesc="Deal 11 damage to ALL enemies for each potion you carry. "
                           "Exhaust.",
                     fx=lambda cb, k, t: cb.overdose(k.v(8, 11))),
    "elixir_of_ash": dict(name="Elixir of Ash", type="POWER", cost=1, rarity="rare",
                          desc="Whenever you brew a potion, gain 2 Strength.",
                          udesc="Whenever you brew a potion, gain 3 Strength.",
                          fx=lambda cb, k, t: cb.apply(cb.player, "brewmaster", k.v(2, 3))),

    # ══ hexbinder ══════════════════════════════════════════════════════════
    # ── starter ──
    "binding_word": dict(name="Binding Word", type="ATTACK", cost=1, targeted=True,
                         rarity="starter",
                         desc="Deal 5 damage. Apply 1 Weak and 1 Vulnerable.",
                         udesc="Deal 7 damage. Apply 1 Weak and 1 Vulnerable.",
                         fx=lambda cb, k, t: (cb.player_attack(t, k.v(5, 7)),
                                              cb.apply(t, "weak", 1),
                                              cb.apply(t, "vulnerable", 1))),
    # ── common ──
    "hex_bolt": dict(name="Hex Bolt", type="ATTACK", cost=1, targeted=True,
                     desc="Deal 7 damage. Apply 1 Weak.",
                     udesc="Deal 9 damage. Apply 2 Weak.",
                     fx=lambda cb, k, t: (cb.player_attack(t, k.v(7, 9)),
                                          cb.apply(t, "weak", k.v(1, 2)))),
    "curse_of_frailty": dict(name="Curse of Frailty", type="SKILL", cost=0, targeted=True,
                             desc="Apply 2 Frail.", udesc="Apply 3 Frail.",
                             fx=lambda cb, k, t: cb.apply(t, "frail", k.v(2, 3))),
    "wither": dict(name="Wither", type="ATTACK", cost=1, targeted=True,
                   desc="Deal 6 damage. The enemy loses 1 Strength.",
                   udesc="Deal 8 damage. The enemy loses 2 Strength.",
                   fx=lambda cb, k, t: (cb.player_attack(t, k.v(6, 8)),
                                        cb.apply(t, "strength", -k.v(1, 2)))),
    "warding_sigil": dict(name="Warding Sigil", type="SKILL", cost=1,
                          desc="Gain 7 Block.", udesc="Gain 10 Block.",
                          fx=lambda cb, k, t: cb.gain_block(cb.player, k.v(7, 10))),
    "unravel": dict(name="Unravel", type="ATTACK", cost=1, targeted=True,
                    desc="Deal 4 damage. Deal 3 more for each debuff stack on the target.",
                    udesc="Deal 5 damage. Deal 4 more for each debuff stack on the target.",
                    fx=lambda cb, k, t: cb.player_attack(
                        t, k.v(4, 5) + k.v(3, 4) * cb.debuff_stacks(t))),
    "sap_will": dict(name="Sap Will", type="SKILL", cost=1, targeted=True,
                     desc="Apply 2 Weak. Draw 1 card.", udesc="Apply 3 Weak. Draw 1 card.",
                     fx=lambda cb, k, t: (cb.apply(t, "weak", k.v(2, 3)), cb.draw(1))),
    "evil_eye": dict(name="Evil Eye", type="SKILL", cost=1, targeted=True,
                     desc="Apply 2 Vulnerable. Gain 4 Block.",
                     udesc="Apply 3 Vulnerable. Gain 6 Block.",
                     fx=lambda cb, k, t: (cb.apply(t, "vulnerable", k.v(2, 3)),
                                          cb.gain_block(cb.player, k.v(4, 6)))),
    "bad_omen": dict(name="Bad Omen", type="SKILL", cost=0, targeted=True,
                     desc="Apply 1 Weak and 1 Vulnerable.",
                     udesc="Apply 2 Weak and 2 Vulnerable.",
                     fx=lambda cb, k, t: (cb.apply(t, "weak", k.v(1, 2)),
                                          cb.apply(t, "vulnerable", k.v(1, 2)))),
    "spite": dict(name="Spite", type="ATTACK", cost=1, targeted=True,
                  desc="Deal 11 damage. Gain 1 Vulnerable.",
                  udesc="Deal 15 damage. Gain 1 Vulnerable.",
                  fx=lambda cb, k, t: (cb.player_attack(t, k.v(11, 15)),
                                       cb.apply(cb.player, "vulnerable", 1))),
    "blight_touch": dict(name="Blight Touch", type="ATTACK", cost=1, targeted=True,
                         desc="Deal 5 damage. Apply 2 Frail.",
                         udesc="Deal 7 damage. Apply 3 Frail.",
                         fx=lambda cb, k, t: (cb.player_attack(t, k.v(5, 7)),
                                              cb.apply(t, "frail", k.v(2, 3)))),
    "chain_word": dict(name="Chain Word", type="SKILL", cost=1, targeted=True,
                       desc="Apply 1 Weak, 1 Vulnerable and 1 Frail.",
                       udesc="Apply 2 Weak, 2 Vulnerable and 2 Frail.",
                       fx=lambda cb, k, t: [cb.apply(t, key, k.v(1, 2))
                                            for key in ("weak", "vulnerable", "frail")]),
    # ── uncommon ──
    "hexbloom": dict(name="Hexbloom", type="POWER", cost=1, rarity="uncommon",
                     desc="Whenever you weaken an enemy, deal 2 damage to it.",
                     udesc="Whenever you weaken an enemy, deal 3 damage to it.",
                     fx=lambda cb, k, t: cb.apply(cb.player, "hexbloom", k.v(2, 3))),
    "long_grudge": dict(name="Long Grudge", type="SKILL", cost=1, ucost=0, targeted=True,
                        rarity="uncommon", exhaust=True,
                        desc="The enemy's debuffs no longer wear off. Exhaust.",
                        udesc="The enemy's debuffs no longer wear off. Exhaust.",
                        fx=lambda cb, k, t: cb.apply(t, "entrenched", 1)),
    "mass_hysteria": dict(name="Mass Hysteria", type="SKILL", cost=2, rarity="uncommon",
                          exhaust=True,
                          desc="Apply 3 Weak, 3 Vulnerable and 3 Frail to ALL enemies. "
                               "Exhaust.",
                          udesc="Apply 4 Weak, 4 Vulnerable and 4 Frail to ALL enemies. "
                                "Exhaust.",
                          fx=lambda cb, k, t: [cb.apply(e, key, k.v(3, 4))
                                               for e in cb.living()
                                               for key in ("weak", "vulnerable", "frail")]),
    "feed_on_fear": dict(name="Feed on Fear", type="ATTACK", cost=2, targeted=True,
                         rarity="uncommon",
                         desc="Deal 12 damage. Heal 2 HP for each debuff stack on the "
                              "target.",
                         udesc="Deal 15 damage. Heal 3 HP for each debuff stack on the "
                               "target.",
                         fx=lambda cb, k, t: (cb.heal(cb.player,
                                                      k.v(2, 3) * cb.debuff_stacks(t)),
                                              cb.player_attack(t, k.v(12, 15)))),
    "wracking_pain": dict(name="Wracking Pain", type="ATTACK", cost=1, rarity="uncommon",
                          desc="Deal 5 damage and apply 1 Weak to ALL enemies.",
                          udesc="Deal 7 damage and apply 2 Weak to ALL enemies.",
                          fx=lambda cb, k, t: [(cb.player_attack(e, k.v(5, 7)),
                                                cb.apply(e, "weak", k.v(1, 2)))
                                               for e in cb.living()]),
    "voodoo_pin": dict(name="Voodoo Pin", type="ATTACK", cost=1, targeted=True,
                       rarity="uncommon",
                       desc="Deal damage equal to 4 times the target's debuff stacks.",
                       udesc="Deal damage equal to 6 times the target's debuff stacks.",
                       fx=lambda cb, k, t: cb.player_attack(t, k.v(4, 6)
                                                            * cb.debuff_stacks(t))),
    "dread_aura": dict(name="Dread Aura", type="POWER", cost=2, ucost=1, rarity="uncommon",
                       desc="At the start of each turn, apply 1 Weak to ALL enemies.",
                       udesc="At the start of each turn, apply 1 Weak to ALL enemies.",
                       fx=lambda cb, k, t: cb.apply(cb.player, "dreadaura", 1)),
    "sigil_ward": dict(name="Sigil Ward", type="SKILL", cost=1, rarity="uncommon",
                       desc="Gain 8 Block. Apply 1 Frail to ALL enemies.",
                       udesc="Gain 11 Block. Apply 2 Frail to ALL enemies.",
                       fx=lambda cb, k, t: (cb.gain_block(cb.player, k.v(8, 11)),
                                            [cb.apply(e, "frail", k.v(1, 2))
                                             for e in cb.living()])),
    "malediction": dict(name="Malediction", type="ATTACK", cost=2, targeted=True,
                        rarity="uncommon",
                        desc="Deal 10 damage. Apply 2 Weak and 2 Vulnerable.",
                        udesc="Deal 13 damage. Apply 3 Weak and 3 Vulnerable.",
                        fx=lambda cb, k, t: (cb.player_attack(t, k.v(10, 13)),
                                             cb.apply(t, "weak", k.v(2, 3)),
                                             cb.apply(t, "vulnerable", k.v(2, 3)))),
    "borrowed_time": dict(name="Borrowed Time", type="SKILL", cost=0, rarity="uncommon",
                          desc="Draw 2 cards. Gain 1 Vulnerable.",
                          udesc="Draw 3 cards. Gain 1 Vulnerable.",
                          fx=lambda cb, k, t: (cb.draw(k.v(2, 3)),
                                               cb.apply(cb.player, "vulnerable", 1))),
    # ── rare ──
    "litany_of_names": dict(name="Litany of Names", type="POWER", cost=2, rarity="rare",
                            desc="Gain 3 Hexbloom.", udesc="Gain 4 Hexbloom.",
                            fx=lambda cb, k, t: cb.apply(cb.player, "hexbloom", k.v(3, 4))),
    "evil_within": dict(name="Evil Within", type="POWER", cost=2, rarity="rare",
                        desc="At the start of each turn, deal 6 damage to every enemy "
                             "carrying 3 or more debuff stacks.",
                        udesc="At the start of each turn, deal 9 damage to every enemy "
                              "carrying 3 or more debuff stacks.",
                        fx=lambda cb, k, t: cb.apply(cb.player, "evilwithin", k.v(6, 9))),
    "unmaking": dict(name="Unmaking", type="ATTACK", cost=2, targeted=True, rarity="rare",
                     exhaust=True,
                     desc="Deal damage equal to 7 times the target's debuff stacks. Exhaust.",
                     udesc="Deal damage equal to 10 times the target's debuff stacks. "
                           "Exhaust.",
                     fx=lambda cb, k, t: cb.player_attack(t, k.v(7, 10)
                                                          * cb.debuff_stacks(t))),
    "scapegoat": dict(name="Scapegoat", type="SKILL", cost=1, ucost=0, targeted=True,
                      rarity="rare",
                      desc="Move your Weak, Vulnerable and Frail onto an enemy.",
                      udesc="Move your Weak, Vulnerable and Frail onto an enemy.",
                      fx=lambda cb, k, t: cb.scapegoat(t)),
    "grim_tally": dict(name="Grim Tally", type="ATTACK", cost=3, rarity="rare",
                       desc="Deal 8 damage to ALL enemies. Apply 2 Weak, 2 Vulnerable "
                            "and 2 Frail to ALL enemies.",
                       udesc="Deal 11 damage to ALL enemies. Apply 3 Weak, 3 Vulnerable "
                             "and 3 Frail to ALL enemies.",
                       fx=lambda cb, k, t: [(cb.player_attack(e, k.v(8, 11)),
                                             [cb.apply(e, key, k.v(2, 3))
                                              for key in ("weak", "vulnerable", "frail")])
                                            for e in cb.living()]),
    "binding_circle": dict(name="Binding Circle", type="POWER", cost=3, ucost=2,
                           rarity="rare",
                           desc="At the start of each turn, apply 1 Weak, 1 Vulnerable "
                                "and 1 Frail to ALL enemies.",
                           udesc="At the start of each turn, apply 1 Weak, 1 Vulnerable "
                                 "and 1 Frail to ALL enemies.",
                           fx=lambda cb, k, t: cb.apply(cb.player, "bindingcircle", 1)),
    "witching_hour": dict(name="Witching Hour", type="SKILL", cost=2, ucost=1,
                          rarity="rare", exhaust=True,
                          desc="Double every debuff on ALL enemies. Exhaust.",
                          udesc="Double every debuff on ALL enemies. Exhaust.",
                          fx=lambda cb, k, t: cb.double_debuffs()),
}
