"""Per-client runs.

The server used to hold exactly one module-global `Session` behind one global
`Lock`, so a second browser tab hijacked the first player's run and every request
serialised behind every other. Each client now gets its own run, its own lock,
and a save file it can be resumed from.
"""

import json
import os
import secrets
import tempfile
import threading
import time

from ..engine.run import Run

COOKIE = "sid"
DEFAULT_TTL = 12 * 3600      # drop idle runs after this long
DEFAULT_MAX = 64             # and never hold more than this many at once


class Session:
    """One run plus the lock that serialises access to it."""

    def __init__(self, sid, run):
        self.sid = sid
        self.run = run
        self.lock = threading.RLock()
        self.touched = time.monotonic()

    def touch(self):
        self.touched = time.monotonic()


class SessionStore:
    def __init__(self, directory=None, ttl=DEFAULT_TTL, max_sessions=DEFAULT_MAX):
        self.dir = directory
        self.ttl = ttl
        self.max_sessions = max_sessions
        self._sessions = {}
        self._guard = threading.Lock()
        if self.dir:
            os.makedirs(self.dir, exist_ok=True)

    # ── identity ──
    @staticmethod
    def new_sid():
        return secrets.token_urlsafe(24)

    def _path(self, sid):
        # sid is generated by us and URL-safe, but never build a path from an
        # untrusted one — reject anything that could escape the directory.
        if not self.dir or "/" in sid or "\\" in sid or sid.startswith("."):
            return None
        return os.path.join(self.dir, f"{sid}.json")

    # ── lookup ──
    def get(self, sid):
        """An existing session, restoring from disk if it has been evicted."""
        if not sid:
            return None
        with self._guard:
            session = self._sessions.get(sid)
            if session:
                session.touch()
                return session
        run = self._load(sid)
        if run is None:
            return None
        return self._insert(sid, run)

    def create(self, cls=None, seed=None, sid=None):
        sid = sid or self.new_sid()
        return self._insert(sid, Run(cls, seed=seed))

    def _insert(self, sid, run):
        session = Session(sid, run)
        with self._guard:
            self._sessions[sid] = session
            self._evict()
        return session

    def _evict(self):
        """Caller holds _guard. Drop expired sessions, then the oldest if over cap."""
        now = time.monotonic()
        for sid, s in list(self._sessions.items()):
            if now - s.touched > self.ttl:
                del self._sessions[sid]
        while len(self._sessions) > self.max_sessions:
            oldest = min(self._sessions.values(), key=lambda s: s.touched)
            del self._sessions[oldest.sid]

    def count(self):
        with self._guard:
            return len(self._sessions)

    # ── persistence ──
    def save(self, session):
        path = self._path(session.sid)
        if not path:
            return
        blob = json.dumps(session.run.to_dict())
        fd, tmp = tempfile.mkstemp(dir=self.dir, suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(blob)
            os.replace(tmp, path)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise

    def _load(self, sid):
        path = self._path(sid)
        if not path or not os.path.exists(path):
            return None
        try:
            with open(path, encoding="utf-8") as f:
                return Run.from_dict(json.load(f))
        except (OSError, ValueError, KeyError):
            return None

    def discard(self, sid):
        with self._guard:
            self._sessions.pop(sid, None)
        path = self._path(sid)
        if path:
            try:
                os.unlink(path)
            except OSError:
                pass
